open-telemetry/semantic-conventions

- Makefile
- internal/tools/schema_check.sh
- semantic_conventions/README.md
- semantic_conventions/http-common.yaml
- specification/trace/semantic_conventions/http.md
- specification/trace/semantic_conventions/instrumentation/aws-lambda.md
Updating a few overlooked usages of `http.method` to `http.request.method` and a few other small fixes
> Editorial: minor fixes for HTTP spec

- CHANGELOG.md
- semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
Successor of https://github.com/open-telemetry/opentelemetry-specification/pull/3487
> describe JVM CPU metrics

- CHANGELOG.md
That would be [#3458](https://github.com/open-telemetry/opentelemetry-specification/pull/3458), which had been included in the metrics section (instead of semantic conventions) of the CHANGELOG.
> Update CHANGELOG with missing entry.

- CHANGELOG.md
- semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
- specification/metrics/semantic_conventions/runtime-environment-metrics.md
Fixes #49
Clarifies that `process.runtime.jvm.threads.count` refers to platform threads, as opposed to virtual threads.
> Clarify `process.runtime.jvm.threads.count` refers to platform threads

- CHANGELOG.md
- specification/metrics/semantic_conventions/http-metrics.md
The purpose of this PR is to clarify one of the easier questions that came up as part of https://github.com/open-telemetry/opentelemetry-specification/issues/3520.
I don't think I worded it great, if anyone has suggestions 🙇‍♂️
> HTTP duration metrics should match HTTP span duration

- CHANGELOG.md
- semantic_conventions/resource/cloud.yaml
- specification/resource/semantic_conventions/cloud.md
Adds [Google Bare Metal Solution](https://cloud.google.com/bare-metal) as an allow-listed cloud platform. 
Please let me know if there's anything else I need to do to make this change properly.
> Add Google Bare Metal Solution as a cloud platform

- CHANGELOG.md
- schemas/1.21.0
- semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
- specification/metrics/semantic_conventions/runtime-environment-metrics.md
Fixes #42
Renames `process.runtime.jvm.cpu.utilization` to `process.runtime.jvm.cpu.recent_utilization` to make it clear that this is not "utilization since last measurement" (or "utilization since start").
> Rename `process.runtime.jvm.cpu.utilization` to `process.runtime.jvm.cpu.recent_utilization`

- CHANGELOG.md
- specification/trace/semantic_conventions/http.md
Addresses part of https://github.com/open-telemetry/opentelemetry-specification/issues/3520
> Clarify HTTP client duration

- specification/resource/semantic_conventions/cloud_provider/gcp/cloud_run.md
Fix `Description` section for GCP Cloud Run Job execution.
Related issues:
[Add detail for GCP Cloud Run Job execution](https://github.com/open-telemetry/opentelemetry-specification/pull/3378)
> Fix 'Description' section for GCP Cloud Run Job execution

- CHANGELOG.md
- specification/metrics/semantic_conventions/http-metrics.md
- specification/metrics/semantic_conventions/rpc-metrics.md
- specification/trace/semantic_conventions/database.md
- specification/trace/semantic_conventions/http.md
- specification/trace/semantic_conventions/messaging.md
- specification/trace/semantic_conventions/rpc.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3488
Port of https://github.com/open-telemetry/opentelemetry-specification/pull/3492 from before the repo split.
> Clarify that OTEL_SEMCONV_STABILITY_OPT_IN is a comma-separated list of values

- specification/resource/semantic_conventions/cloud_provider/gcp/README.md
Add a lacking `Compute Engine` link to the Services section.
> Add lacking Compute Engine link to the Services section

- CHANGELOG.md
- semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
- specification/metrics/semantic_conventions/runtime-environment-metrics.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3490
Adds `process.runtime.jvm.cpu.time` metric.
> Add `process.runtime.jvm.cpu.time` metric

- CHANGELOG.md
- semantic_conventions/trace/http.yaml
- specification/trace/semantic_conventions/http.md
Fixes #112
Aligns the requirement level of `url.query` with the requirement level of `url.path`.
It was also the previous behavior when those two attributes were combined in the single field `http.target`, and appears to have been a bug that slipped into https://github.com/open-telemetry/opentelemetry-specification/pull/3355 when that field was split into `url.path` and `url.query`.
> Make `url.query` conditionally required for HTTP spans

- CHANGELOG.md
- semantic_conventions/http-common.yaml
- semantic_conventions/trace/http.yaml
- specification/metrics/semantic_conventions/http-metrics.md
- specification/trace/semantic_conventions/http.md
Moving in https://github.com/open-telemetry/opentelemetry-specification/pull/3478.
- restricts `http.request.method` values to well-known names
- requires to use `other` for unknown methods to prevent cardinality explosion if a malicious (or buggy) client sends custom and dynamic methods.
- allows recording actual method value in the `http.request.original_method`
There was a discussion on the original PR and at HTTP SIG meeting, the summary and options are in the comments.
> Limit HTTP request method cardinality: original_method (option A)

- CHANGELOG.md
- semantic_conventions/resource/service.yaml
- semantic_conventions/resource/service_experimental.yaml
- specification/resource/semantic_conventions/README.md
Reopening this from the related Specification PR. 
cc @jsuereth
> Mark service.version as stable.

- semantic_conventions/trace/http.yaml
- specification/trace/semantic_conventions/http.md
> Change `server.address` and `server.port` from required to recommended on HTTP Server Spans

- CHANGELOG.md
Changelog introduced in https://github.com/open-telemetry/opentelemetry-specification/pull/3402 refers to a nonexistent attribute.
> Fix CHANGELOG.md (server.name does not exist)

- semantic_conventions/metrics/process-runtime-jvm-metrics-experimental.yaml
- semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
- specification/metrics/semantic_conventions/runtime-environment-metrics.md
> Add 'as reported by the JVM' qualifier to JVM cpu metrics

- CHANGELOG.md
- specification/metrics/semantic_conventions/http-metrics.md
- specification/trace/semantic_conventions/http.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3279
> Mark initial set of HTTP semantic conventions as frozen

- CHANGELOG.md
Looks like an leftover from the repo move.
> correct link in changelog

- CHANGELOG.md
- specification/metrics/semantic_conventions/runtime-environment-metrics.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3416
Mark `process.runtime.jvm.system.cpu.load_1m` and `process.runtime.jvm.system.cpu.utilization` metris as opt-in
> JVM cpu metrics opt-in

- CHANGELOG.md
- schemas/1.21.0
- semantic_conventions/trace/messaging.yaml
- specification/trace/semantic_conventions/messaging.md
Port from https://github.com/open-telemetry/opentelemetry-specification/pull/3450
CC @lmolkova 
--
Fixes open-telemetry/opentelemetry-specification#3196
- Removes `messaging.source` namespace. `Destination` and `source` namespaces are defined in ECS and unrelated to messaging. Removed to allow attribute reuse across signals (e.g. logs), to decrease confusion with ECS source, and resolve some usability issues with source/destination 
- Not removing `messaging.destination` because it's widely used in messaging 
- Introduces `destination_original`: in some cases when a message is routed,  consumer also knows the original destination and the destination it received a message from. With `messaging.source` removed, we need another namespace for the original destination.
> Messaging: Remove `messaging.source.*` attributes

- CHANGELOG.md
- semantic_conventions/trace/database.yaml
- specification/trace/semantic_conventions/README.md
- specification/trace/semantic_conventions/database.md
- specification/trace/semantic_conventions/instrumentation/elasticsearch.md
This PR originated as a [PR in the opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/pull/3358) repo.
The outstanding discussion point from that PR was regarding the path forward for the existing Elasticsearch client instrumentations:
- .NET: No concerns about updating their instrumentation to adopt these semantic conventions
- Python: No concerns about updating their instrumentation to adopt these semantic conventions
- Java: request to understand the complexity of updating the instrumentation by opening a PR with the changes
We are in the process of figuring out the path forward for the Java instrumentation and I'll update here when we have a plan.
Two instrumentations in progress that will use these semantic conventions:
- PHP
- …
> Add semantic conventions for Elasticsearch client instrumentation

- Makefile
Current PRs will not spot table generation issues because the make task still points to `/specification`.
> Fix path of md table generation make task

- CHANGELOG.md
- docs/database/elasticsearch.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- docs/url/README.md
- docs/url/url.md
As [mentioned](https://cloud-native.slack.com/archives/C041APFBYQP/p1688710620404769) by @AlexanderWert the `url.md` file is missing in the `semantic-conventions` repository.
The [URL semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/url.md) currently resides in the `specification/common` directory of the `specification` repository. 
This PR is to add it in the `semantic-conventions` repository.
> Add markdown file for url semantic conventions

- docs/resource/cloud_provider/README.md
Publishing the docs to the OTel website requires that all sections have a README.md file. This adds a README.md that is missing from https://github.com/open-telemetry/semantic-conventions/tree/main/docs/resource/cloud_provider.
@jsuereth @joaopgrassi 
/cc @svrnm @cartermp
> [editorial] Add missing `README.md` for Resource Cloud Provider semconv

- docs/faas/faas-spans.md
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/2721
- Drops unnecessary hash to page title, instead uses direct link to page. (The problem with the use of a hash to the title, is that it doesn't exist when the page is published on the OTel website).
> [editorial] Link directly to page, not to page's title

- .github/workflows/checks.yml
- CONTRIBUTING.md
- Makefile
- docs/general/general-attributes.md
- docs/general/trace-general.md
- docs/rpc/rpc-metrics.md
- docs/rpc/rpc-spans.md
- gulpfile.js
- package.json
- Adds a Gulp task named `lint-md` to run `markdownlint`
- The **task runs in less than 1.5 seconds** over the same files as the `markdownlint` make target, which takes much longer, when run from the command line
- Fixes the errors reported by `markdownlint` Gulp task. I'm unsure why, with the same config, the CLI misses those errors
- Replaces the call to the `markdownlint` CLI with the Gulp task in the `markdownlint` job
> [editorial] markdownlint in less then 1.5 sec

- docs/faas/aws-lambda.md
Fixes #157
`messaging.source.name` was merged with `messaging.destination.name` attribute in #100 and `messaging.*.kind` were removed in https://github.com/open-telemetry/opentelemetry-specification/pull/3214, and AWS  lambda examples are now out of date.
> Editorial: Remove overlooked messaging.source attributes from aws lambda examples

- CHANGELOG.md
- docs/system/runtime-environment-metrics.md
- model/metrics/process-runtime-jvm-metrics-experimental.yaml
Fix the unit of metric.process.runtime.jvm.system.cpu.load_1m to be "{core}"
This is particularly obvious when you see that the the metric name is converted to `process_runtime_jvm_system_cpu_load_1m_ratio{}` in prometheus.
> Fix the unit of metric.process.runtime.jvm.system.cpu.load_1m to be {run_queue_item}

- gulpfile.js
- Followup to #193
- Ensures that _all_ files are checked by markdownlint, and that if issues are detected, then the overall task fails at the end
> [editorial][CI] Ensure markdownlint has proper exit status

- CONTRIBUTING.md
Specifically:
- Make sure folks know where to put new schema-file changes
- Make sure it's documents that you NEED to use YAML files for attribute/metric definitions right now
- Call out a bit about Hugo, even if we plan to change it going forward.
- Make sure folks know to update the CHANGELOG.md file.
> Update contributing documentation for restructuring of repository

- README.md
Based on the offline discussion with other maintainers, @AlexanderWert has demonstrated strong commitment and great expertise, we would like to invite @AlexanderWert as an Approver of the project.
* PRs https://github.com/open-telemetry/semantic-conventions/pulls?q=is%3Apr+author%3AAlexanderWert+.
* OTEPs https://github.com/open-telemetry/oteps/blob/main/text/0199-support-elastic-common-schema-in-opentelemetry.md
@AlexanderWert @arminru @jsuereth @tigrannajaryan
> Add Alexander Wert as an Approver

- .vscode/settings.json
- Makefile
- internal/tools/schema_check.sh
- model/README.md
See https://github.com/open-telemetry/build-tools/releases/tag/v0.19.0 and https://github.com/open-telemetry/build-tools/releases/tag/v0.20.0.
> Bump semantic conventions tooling to v0.20.0

- CHANGELOG.md
- docs/system/system-metrics.md
ref: https://github.com/open-telemetry/opentelemetry-specification/issues/3556
Closes #98
> Add system.cpu.physical.count and system.cpu.logical.count metrics

- CHANGELOG.md
- docs/general/metrics.md
- docs/http/http-metrics.md
- model/metrics/http.yaml
- schema-next.yaml
> Rename `http.*.duration` to `http.*.request.duration`

- README.md
@joaopgrassi has been [actively contributing to the semantic-conventions](https://github.com/open-telemetry/semantic-conventions/pulls?q=+is%3Apr+author%3Ajoaopgrassi), based on the offline discussions with the current maintainers, we would like to invite Joao as a maintainer of this project.
@arminru @jsuereth
FYI @open-telemetry/specs-semconv-approvers.
> Move Joao Grassi from approver to maintainer

- docs/general/attributes.md
- model/destination.yaml
Based on @Oberon00's https://github.com/open-telemetry/semantic-conventions/issues/206#issue-1819655650
> * destination.address: "Peer address, for example IP address or UNIX socket name." _(why does it use the removed term "peer" here? That would mean something rather different, and would match our old remote/local concept)_
> Update destination attribute briefs

- CHANGELOG.md
- docs/system/runtime-environment-metrics.md
- model/metrics/process-runtime-jvm-metrics-experimental.yaml
- model/metrics/process-runtime-jvm-metrics.yaml
- schema-next.yaml
Fixes #227
I can split these metrics out from `runtime-environment-metrics.md` into `jvm-metrics.md` either in this PR or in a follow-up PR.
Renames all JVM metrics from `process.runtime.jvm.*` to `jvm.*`.
> Rename all JVM metrics from process.runtime.jvm.* to jvm.*

- docs/database/database-spans.md
- docs/database/elasticsearch.md
- docs/general/attributes.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- docs/messaging/messaging-spans.md
- docs/rpc/rpc-metrics.md
- docs/rpc/rpc-spans.md
- model/client.yaml
- model/server.yaml
Attempt to improve symmetry of
* `(client|server).(address|port)`
* `(client|server).socket.(address|port)`
based on @Oberon00's https://github.com/open-telemetry/semantic-conventions/issues/206#issue-1819655650.
I haven't (intentionally) changed any definitions, so I don't think change log is needed, but not a problem to add.
> Improve symmetry in client/server address/port text

- CHANGELOG.md
- docs/general/attributes.md
- docs/system/runtime-environment-metrics.md
- model/metrics/process-runtime-jvm-metrics-experimental.yaml
- model/metrics/process-runtime-jvm-metrics.yaml
- model/trace/general.yaml
- schema-next.yaml
Successor of https://github.com/open-telemetry/opentelemetry-specification/pull/3464#pullrequestreview-1424803956
Fixes #61
> add namespace to jvm metric attributes

- docs/database/elasticsearch.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- model/http-common.yaml
Fixes #232
Removes this portion of `http.request.method` note:
> and, except if reporting a metric, [instrumentation] MUST set the exact method received in the request line as value of the `http.request.method_original` attribute
This portion caused some confusion in #231, and it seems that we can just remove it, since `http.request.method_original` is already conditionally required "If and only if it's different than `http.request.method`".
> Remove unnecessary portion of http.request.method note

- CHANGELOG.md
- docs/database/database-spans.md
- docs/http/README.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- docs/messaging/messaging-spans.md
- docs/rpc/rpc-metrics.md
- docs/rpc/rpc-spans.md
Fixes #240
Clarify that `http/dup` has higher precedence than `http` in case both values are present in user supplied `OTEL_SEMCONV_STABILITY_OPT_IN` value.
> `http/dup` has higher precedence than `http` in `OTEL_SEMCONV_STABILITY_OPT_IN`

- CHANGELOG.md
- docs/system/runtime-environment-metrics.md
- model/metrics/process-runtime-jvm-metrics.yaml
- schema-next.yaml
Remove pluralization from JVM metric namespaces.
Related to https://github.com/open-telemetry/semantic-conventions/issues/212 and https://github.com/open-telemetry/opentelemetry-specification/pull/3658
> Remove pluralization from JVM metric namespaces

- CHANGELOG.md
- docs/http/http-metrics.md
- model/metrics/http.yaml
Similar motivation to #275
Simplify HTTP metric briefs
> Simplify HTTP metric briefs

- docs/database/database-spans.md
- docs/http/README.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- docs/messaging/messaging-spans.md
- docs/rpc/rpc-metrics.md
- docs/rpc/rpc-spans.md
Clarification inspired by the following discussion https://github.com/open-telemetry/opentelemetry-dotnet/pull/4766#discussion_r1300370859.
This text shows up in a lot of places. I can update them all, but wanted to get an initial review of the text here before I copy it everywhere. I assume this will not need to be updated in the specification repo once https://github.com/open-telemetry/opentelemetry-specification/pull/3667 is merged.
@trask
> Clarify stabilization plan does not just apply to attributes

- README.md
Fixes #
Updating the `doc` reference to `docs` as per the folder's actually name.
I feel like this is pretty insignificant and a changelog entry isn't required. Do let me know if otherwise!
> chore: fix doc reference to docs

- CHANGELOG.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- model/error.yaml
- model/http-common.yaml
- model/metrics/http.yaml
Fixes #204 
**Proposal:**
- Reserve an attribute for the error code when response code was not received (or reading response body has failed) - `error.type`  (TBD)
- ~~Start with a small, non-controversial set of error types common across HTTP clients in different languages~~. Don't try to unify common errors initially. Even things like timeout (vs cancellation) can be controversial.
- Define 'other' as a dimension cap
- Allow instrumentations to report custom (known, documented, low-cardinality) error types
- If we see similarities in error types across clients/languages, we can consider adding common valuesit into the enum even after HTTP semconv goes stable
(naming and common error suggestions are welcome!)
**Error rate queries**
- `rate(http_request_duration_count{error_type!=""}[1m]) …
> Introduce request error type attribute

- .vscode/settings.json
- Makefile
- internal/tools/schema_check.sh
- model/README.md
This PR bumps up the build-tools dependency to the newest one: https://github.com/open-telemetry/build-tools/releases/tag/v0.21.0.
Related to https://github.com/open-telemetry/semantic-conventions/pull/125#discussion_r1321373318
> Bump semantic conventions tooling to v0.21.0

- model/metrics/system-metrics.yaml
I noticed a warning in PRs related to the recently merged #89  yaml model for system metrics. I left a misaligned comment and GitHub UI complains about it:
> Fix System metrics yaml warning

- CHANGELOG.md
- docs/messaging/messaging-spans.md
- model/trace/messaging.yaml
- schema-next.yaml
Fixes open-telemetry/specification#1053
As described in open-telemetry/specification#1053, attribute sets for http, messaging, and rpc describe body or payload sizes in different way. The changes in this PR make those size descriptions consistent for messaging and http, now for both ending in `.size`.
Furthermore, based on discussions in the messaging workgroup, the ambiguous term "payload" is defined (a payload can refer to both a single message and a batch, and always includes metadata).
The attribute `messaging.message.payload_compressed_size_bytes` is dropped, as the value it provides is not clear.
> Make messaging payload attributes consistent with other conventions

- docs/http/http-metrics.md
- docs/http/http-spans.md
- model/http-common.yaml
- model/metrics/http.yaml
Improves `error.type` wording in HTTP semconv to avoid confusion that "string representation of the status code" could mean what we didn't want it to mean (the status description).
> Improve `error.type` wording in HTTP semconv

- CHANGELOG.md
- CONTRIBUTING.md
- docs/system/system-metrics.md
- model/metrics/system-metrics.yaml
Fixes #257
Add definition for a single metric `system.linux.memory.available`.
* [yes ] [CONTRIBUTING.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md) guidelines followed.
* [yes] [CHANGELOG.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CHANGELOG.md) updated for non-trivial changes.
* [not needed] [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.
> Add system.linux.memory.available metric

- CHANGELOG.md
- docs/http/http-metrics.md
- model/metrics/http.yaml
Fixes #356
Adds `url.scheme` to HTTP client metrics
> Add url.scheme to http client metrics

- CHANGELOG.md
- docs/http/http-metrics.md
- docs/rpc/rpc-metrics.md
- model/metrics/http.yaml
- model/metrics/rpc-metrics.yaml
Fixes #341 
Removes `server.socket.address` attribute from http and rpc metrics.
> BREAKING: Remove `server.socket.address` attribute from http and rpc metrics

- CHANGELOG.md
- docs/database/database-spans.md
- docs/general/attributes.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- docs/messaging/messaging-spans.md
- docs/rpc/rpc-metrics.md
- docs/rpc/rpc-spans.md
- docs/system/system-metrics.md
- model/network.yaml
Part of #335
Note: please merge #289 first, then I will resolve merge conflicts in this PR
> Improve network briefs

- CHANGELOG.md
- docs/resource/README.md
- model/resource/telemetry_experimental.yaml
- schema-next.yaml
- rename `telemetry.auto.name` resource attribute `telemetry.distro.name` 
- add `telemetry.distro.version` resource attribute
> telemetry.distro.name and telemetry.distro.version

- .github/CODEOWNERS
This adds two paths for the newly minted `@open-telemetry/semconv-mobile-approvers` group:
* `/docs/mobile/` - Where mobile specific conventions will be captured
* `/model/logs/mobile*` - For definitions of mobile events via yaml
Relates to #67, #343, and #348.
> Add semconv-mobile-approvers

- CHANGELOG.md
- docs/http/http-metrics.md
- model/metrics/http.yaml
Fixes #335
Minor improvements to HTTP metric briefs around consistency and brevity.
> Improve HTTP metric briefs

- CONTRIBUTING.md
Borrowing from the specification repo https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#how-to-get-your-pr-merged.
> Require two approvals from different companies before merging the PR

- .markdown_link_check_config.json
Currently the markdown link check if failing on all PRs because of https://web.archive.org/web/20180321091318/http://www.onlamp.com/pub/a/linux/2000/11/16/LinuxAdmin.html. 
The link is not dead but it's really unreliable and takes long to load most of the times. As a first quick fix, we can try increasing the tool timeout. Went with `30s` which may be quite long, but I assume the rest of pages load fast, meaning I think it won't affect the total task duration.
> Increase markdown-link-check timeout

- CHANGELOG.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- model/error.yaml
- model/http-common.yaml
Fixes #386
Clarifies that `error.type` should be the fully-qualified exception class name (if applicable) when it represents an exception type.
> Clarify that `error.type` should be the fully-qualified exception class name (if applicable) when it represents an exception type

- CHANGELOG.md
- docs/http/http-metrics.md
- model/metrics/http.yaml
Adds cardinality warning about two opt-in HTTP metric attributes.
> Add cardinality warning about two opt-in HTTP metric attributes

- docs/messaging/rabbitmq.md
This is a trivial fix: it corrects a documentation typo
> RabbitMQ, not RibbitMQ

- CHANGELOG.md
- docs/http/http-spans.md
- model/http-common.yaml
Part of #385
Makes `server.port` conditionally required on HTTP server semconv when it is not the default for the given `url.scheme` (80/443).
This avoids the question of whether missing `server.port` means default or unknown.
And we expect `server.port` to be available to all HTTP server instrumentation.
> Make `server.port` conditionally required on HTTP server semconv

- CHANGELOG.md
- docs/http/http-spans.md
- model/trace/http.yaml
Fixes #389
`network.transport` is typically derivable from `network.protocol.version`:
* HTTP 1.0, 1.1, 2 --> `tcp`
* HTTP 3 --> `udp`
so it doesn't provide much value to capture in HTTP semconv.
Change `network.transport` from recommended to opt-in in the HTTP semconv.
> Change `network.transport` from recommended to opt-in in the HTTP semconv

- CHANGELOG.md
- docs/http/http-metrics.md
- model/metrics/http.yaml
Missed that only one of the HTTP metrics got updated in #401.
Add cardinality warning about two opt-in HTTP metric attributes to all HTTP metrics.
> Add cardinality warning about two opt-in HTTP metric attributes to all HTTP metrics.

- CHANGELOG.md
- docs/http/http-spans.md
- model/trace/http.yaml
Knowing `ipv4` vs `ipv6` does not seem to be a useful enough piece of data in the scope of HTTP semconv to capture it by default on all HTTP telemetry.
Since there isn't anything to override (brief or note) on `network.type`, this attribute is simply removed from http semconv (unlike in #398 and #402 where the attribute is explicitly included as opt-in).
Fixes #403
Changes `network.type` from recommended to opt-in in the HTTP semconv.
> Remove `network.type` from HTTP semconv (changing it from recommended to opt-in)

- CHANGELOG.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- model/http-common.yaml
`network.protocol.name` is typically `http`, so it doesn't provide much value to capture in HTTP semconv.
Fixes #385
Changes `network.protocol.name` from recommended to opt-in in the HTTP semconv.
> Change `network.protocol.name` from recommended to opt-in in the HTTP semconv

- docs/http/http-metrics.md
- docs/runtime/jvm-metrics.md
- Fixes #419
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/3392
/cc @svrnm
> [editorial] Advisory parameter anchor name fix

- CHANGELOG.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- model/http-common.yaml
- model/metrics/http.yaml
> Factor in `X-Forwarded-Host` / `Forwarded` when capturing `server.address` and `server.port`

- docs/runtime/README.md
As spotted by @chalin in https://github.com/open-telemetry/semantic-conventions/commit/559bf8bd66158dd402ae236141f139ef261b7b20#r130403152, I used the wrong `linkTitle` when I moved this page. Returning to the old one.
> Revert to old `linkTitle` on runtime readme

- docs/http/http-metrics.md
- model/metrics/http.yaml
Makes examples on `url.scheme` on HTTP client metrics HTTP-specific (doesn't happen automatically because of reasons and not build-tool bugs).
> Editorial: Fix url.scheme examples on http client metric

- docs/rpc/rpc-metrics.md
Removes outdated section in rpc-metrics.md that no longer applies.
> Remove outdated section in rpc-metrics.md that no longer applies

- CHANGELOG.md
- docs/http/http-spans.md
Fixes #451
Changes the precedence between `:authority` and `Host` headers when populating `server.address` and `server.port` attributes.
Included in change log under "Fixes" instead of "Breaking" because we don't expect this to have any difference in practice, see https://github.com/open-telemetry/semantic-conventions/issues/451#issuecomment-1781371555.
> Change the precedence between `:authority` and `Host` headers when populating `server.address` and `server.port` attributes

- CHANGELOG.md
- docs/attributes-registry/url.md
- docs/http/http-spans.md
- docs/url/url.md
- model/registry/url.yaml
Removes `url.path` default value.
It looks like this originally came from https://github.com/open-telemetry/opentelemetry-specification/pull/3355/files#r1178675917
I don't think we should treat _missing_ `url.path` attribute as any default value.
We could say something about normalizing empty path `""` to `"/"` if we think that's useful.
> Remove `url.path` default value

- docs/http/http-metrics.md
- model/metrics/http.yaml
Updates text to reflect recent change in #423.
> Update text to reflect recent change in #423

- docs/http/http-metrics.md
- docs/http/http-spans.md
- model/http-common.yaml
- model/trace/http.yaml
Updates `Forwarded` header links to use specific anchors.
(or is there a reason not to use anchors?)
> Update `Forwarded` header links to use specific anchors

- model/registry/http.yaml
Fixes lint warning.
See https://github.com/open-telemetry/semantic-conventions/pull/472#pullrequestreview-1704658579
> Fix lint warning

- CHANGELOG.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- model/http-common.yaml
Fixes #477
Changes `network.protocol.name` from opt-in to conditionally required.
> Change `network.protocol.name` from opt-in to conditionally required

- CHANGELOG.md
- Makefile
- docs/http/http-spans.md
- internal/tools/schema_check.sh
- model/README.md
Follow-up to https://github.com/open-telemetry/build-tools/pull/230
Fixes #422
Change sampling relevant from `MUST` to `SHOULD`.
> Change sampling relevant from MUST to SHOULD (and update build-tools version)

- docs/attributes-registry/messaging.md
- docs/messaging/kafka.md
- docs/messaging/messaging-spans.md
- docs/messaging/rabbitmq.md
- docs/messaging/rocketmq.md
- model/registry/messaging.yaml
- model/trace/messaging.yaml
Refactoring: moves `messaging.*` attributes to the registry
> Moved `messaging.*` attributes to the registry

- CHANGELOG.md
- Makefile
- docs/attributes-registry/http.md
- docs/attributes-registry/network.md
- docs/attributes-registry/url.md
- docs/attributes-registry/user-agent.md
- docs/general/attributes.md
- docs/http/README.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- model/client.yaml
- model/error.yaml
- model/registry/http.yaml
- model/registry/network.yaml
- model/registry/url.yaml
- model/registry/user-agent.yaml
- model/server.yaml
Fixes #82 
* ~~schema-next.yaml~~
> Mark HTTP semantic conventions as stable

- CHANGELOG.md
- schemas/1.23.0
This marks the stability release for HTTP.
Post-this-PR we will not allow "breaking" changes to HTTP attributes marked stable, as they are no longer covered by the transition.
> Staging the 1.23.0 release.

- CHANGELOG.md
- docs/resource/deployment-environment.md
- model/resource/deployment_environment.yaml
To clarify a likely misconception about service identity in the case of multiple environments.
Explain that `deployment.environment` does not impact service identity.
Fixes https://github.com/open-telemetry/semantic-conventions/issues/119
> docs: explain deployment.environment impact on service identity

- docs/attributes-registry/messaging.md
- docs/messaging/README.md
- docs/messaging/gcp-pubsub.md
- docs/messaging/messaging-spans.md
- model/registry/messaging.yaml
Adds gcp_pubsub as a messaging system value
Waiting to sign the CLA until the PR is created. 
Also I ran `make fix`, but it generated some diffs in CONTRIBUTING.md (* -> -) and CHANGELOG.md (whitespace), so I left those out.
Skipped, since it is a trivial change
Skipped since it only affects the docs
> docs(messaging): add gcp_pubsub as a messaging system

- CHANGELOG.md
- docs/attributes-registry/messaging.md
- docs/messaging/messaging-spans.md
- model/registry/messaging.yaml
Follow-up from https://github.com/open-telemetry/semantic-conventions/pull/490#discussion_r1391129817
For consistency with `database.system` changing the `messaging.system` attribute type from string to enum. This also helps with documenting well-known values to be used for different messaging systems.
> Changed `messaging.system` attribute type to an open enum

- model/registry/cloud.yaml
- model/registry/container.yaml
- model/registry/device.yaml
- model/registry/host.yaml
- model/registry/oci.yaml
- model/registry/os.yaml
- model/registry/process.yaml
Fixes broken code generation that assumes that resource attributes are strictly separated from semantic attributes.
> Temp fix for separation of resource and semantic attributes

- model/registry/cloud.yaml
- model/registry/container.yaml
- model/registry/oci.yaml
(cherry picked from commit 2817a7fa5b5d230f70314fdf425e1c468163f1e0)
Related to #533.
> [backport to 1.23.x] Temp fix for separation of resource and semantic attributes (#524)

- .github/workflows/checks.yml
In order to also cover other branches like https://github.com/open-telemetry/semantic-conventions/tree/release/v1.23.x and PRs targeting them.
> [CI] Run checks.yml on all branches

- docs/messaging/kafka.md
Since version 1.17.0 it was updated
It was updated from `messaging.kafka.partition` to `messaging.kafka.destination.partition`: https://github.com/open-telemetry/opentelemetry-specification/blob/main/schemas/1.21.0#L78C9-L78C9
> Use new partition attribute path

- CHANGELOG.md
- docs/database/database-spans.md
- docs/http/README.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- docs/messaging/messaging-spans.md
- docs/rpc/rpc-metrics.md
- docs/rpc/rpc-spans.md
Part of #534
Removes no longer relevant Oct 1 mention from `OTEL_SEMCONV_STABILITY_OPT_IN`.
> Remove Oct 1 mention from `OTEL_SEMCONV_STABILITY_OPT_IN`

- docs/attributes-registry/README.md
- docs/attributes-registry/disk.md
- docs/system/system-metrics.md
With https://github.com/open-telemetry/semantic-conventions/pull/530 we missed the `disk.md` file of the registry for the Disk attributes.
This PR adds this file to the registry.
> Add registry md file for disk attributes

- CONTRIBUTING.md
- README.md
- internal/tools/update_specification_version.sh
In #473 there was some confusion and back and forth regarding links to the specification repo. The confusion was about if links to the spec repo should point to `main` or to a specific tag. 
Today, we don't have any mention in `CONTRIBUTING.md` that links to the spec should point to a tag. Also, it is not clear which version of the spec this repo is targeting. We only have this text in the root readme:
>This repository is currently using [this specification version](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.26.0)
Which can be easily missed since it's not obvious at first sight. 
To improve things, I propose in this PR:
- To add a badge where we can show which spec version we are currently targeting
- Add the requirement to `CONTRIBUTING.md` that links to the …
> Improve visibility of used spec version in the semconv repo

- docs/faas/aws-lambda.md
- docs/messaging/messaging-spans.md
- docs/system/hardware-metrics.md
Fixes #549
Fix some links to the specification repo that were not using the correct tag.
> Fix links still pointing to spec repo main branch

- docs/attributes-registry/db.md
- docs/database/database-spans.md
- model/registry/db.yaml
- model/trace/database.yaml
Fixes # N/A
At GitHub we run MySQL in multi-node clusters and are often interested in knowing the hostname of a node that is executing a query or command.
In order to acheive this we added an attribute to the Trilogy instrumentation named `db.mysql.instance.address` which is populated with the hostname of the node:
<https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/487>
This change adds the attribute to the database model as a MySQL specific connection attribute.
> feat: Add MySQL instance address attribute

- CHANGELOG.md
- docs/resource/process.md
Fixes https://github.com/open-telemetry/opentelemetry-dotnet/issues/1281
Defines what values should be set to `process.runtime.*` attributes for .NET.
Implementation can be found in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1449
* ~~[ ] [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.~~ N/A?
> .NET runtime process resource attributes

- CHANGELOG.md
- schemas/1.23.1
Cherry-picks #538 to main branch.
I believe the schema file at least needs to be on main, otherwise when we release 1.24.0 and the website updates to the v1.24.0 tag, the v1.23.1 schema file will no longer be available.
I personally prefer to merge the patch release notes back to main, but that is not so important if you prefer not to.
Resolves #584
Resolves #533
TODO update the patch release instructions to include this step.
> Cherry-pick 1.23.1 schema file (and release notes) to main

- CHANGELOG.md
- model/metrics/http.yaml
We didn't mark metric definitions as stable in the yaml in #377 🤦‍♀️ 
It has no effect on markdown and is not used by other tooling (yet), so I assume no need to hotfix 1.23.1.
> Editorial: update HTTP request duration metrics stability in yaml (to stable)

- CHANGELOG.md
- docs/runtime/jvm-metrics.md
- model/metrics/jvm-metrics.yaml
Marks JVM metrics stable.
Java Instrumentation 1.32.0 already implements these behind `OTEL_SEMCONV_STABILITY_OPT_IN=jvm`, and we are planning to enable them by default in upcoming Java Instrumentation 2.0: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9963
> Mark JVM metrics stable

- docs/attributes-registry/process.md
- docs/resource/process.md
- model/registry/process.yaml
In process.parent_pid description, change abbreviation to PPID.  PPID is the usual abbreviation for Parent Process ID.
> Fix PPID abbreviation in process attributes description

- model/metrics/jvm-metrics.yaml
Follow-up to #569
Marks JVM metrics stable in yaml too (previously only marked stable in markdown).
> Mark JVM metrics stable in yaml too

- docs/http/http-spans.md
Original conversation in https://cloud-native.slack.com/archives/C041APFBYQP/p1702318670634439
- Remove `?` as it should not exist in `url.query`
- Update example for `url.query` that contains multiple parameters
> Clarify example for url.query

- CHANGELOG.md
- docs/attributes-registry/http.md
- docs/attributes-registry/network.md
- model/registry/deprecated/http.yaml
- model/registry/deprecated/network.yaml
> Use deprecated property instead of stability level

- docs/attributes-registry/exception.md
- docs/exceptions/exceptions-logs.md
- docs/exceptions/exceptions-spans.md
- model/registry/exception.yaml
Marks existing exception semconv as stable.
- These have been defacto stable for years now, with little changes.
- Any changes we want to make going forward *needs* to be non-breaking.
- e.g. we may *add* a  representation of stacktraces that would complement pure strings.
- New Languages are free to add more stacktrace representations
If we're all agreed, I'll update the changelog.
> Stabilize exception semantic conventions.

- .markdown_link_check_config.json
- docs/http/migration-guide.md
Part of #534
Adds a "permanent" (non-blog) location for HTTP semantic convention stability migration guide.
@open-telemetry/docs-approvers I copied this from https://opentelemetry.io/blog/2023/http-conventions-declared-stable/#migration-plan and stripped out the non-markdown stuff. what do you think of rendering this as a new page under https://opentelemetry.io/docs/specs/semconv/http/?
> Add HTTP semantic convention stability migration guide

- docs/system/hardware-metrics.md
- docs/system/process-metrics.md
- docs/system/system-metrics.md
Add a warning to the system semantic conventions to prevent implementations from adopting the breaking changes until the conventions are stabilized. This warning is to be updated once https://github.com/open-telemetry/semantic-conventions/issues/246 is closed.
As discussed in the last system conventions meeting.
cc @jsuereth @open-telemetry/semconv-system-approvers
> Add a warning to the system semantic conventions

- CHANGELOG.md
- docs/resource/README.md
- model/resource/service.yaml
- model/resource/service_experimental.yaml
Reverts #630 based on new discussions after merge.
This reverts commit 7f35c490ca2361d9030c504bcda3213d6d102041.
> Revert "Clarify that service.* conventions apply to all telemetry sources"

- docs/attributes-registry/messaging.md
- model/registry/messaging.yaml
Fixes #640
Similar to how it's done for database attributes, this adds system-specific tags to messaging attributes in the registry and displays attributes by-system in the Markdown.
> Move messaging attributes in registry to system-specific sections

- docs/messaging/messaging-spans.md
- model/trace/messaging.yaml
Fixes #641 
This removes obsolete footnotes - the information that attributes in the `messaging.message` namespace only are relevant to spans representing a single message is already present in the conventions.
To make this more obvious and also to clean up the document structure, the description of messaging sub-namespaces is moved before the table of general attributes.
> Remove obsolete footnotes for messaging attributes

- docs/database/couchdb.md
- model/trace/database.yaml
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/3804
cc @svrnm @theletterf
> [editorial] Fix/adjust link to use https rather than http

- CHANGELOG.md
- docs/messaging/messaging-metrics.md
- docs/messaging/messaging-spans.md
- model/messaging-common.yaml
Fixes #504
This makes the usage of `network.protocol.name` consistent between messaging and HTTP semantic conventions: it is now conditionally required for both metrics and traces if the protocol name isn't obvious for the given messaging system or framework.
This is a breaking change for messaging instrumentations, as a previously recommended attribute is made conditionally required.
> Make `network.protocol.name` conditionally required for messaging

- .github/workflows/stale-pr.yml
I basically copied it from the spec repository. I went with a 15 days period to consider a PR stale. I'm also not sure if the GitHub Token there has the correct permissions.
> Add stale bot workflow

- docs/runtime/jvm-metrics.md
I missed these in #569.
The yaml for these 4 metrics are already tagged with `stability: stable`:
https://github.com/open-telemetry/semantic-conventions/blob/13a8238b4dcdd4261751b16012edef6388654f86/model/metrics/jvm-metrics.yaml#L133
https://github.com/open-telemetry/semantic-conventions/blob/13a8238b4dcdd4261751b16012edef6388654f86/model/metrics/jvm-metrics.yaml#L141
https://github.com/open-telemetry/semantic-conventions/blob/13a8238b4dcdd4261751b16012edef6388654f86/model/metrics/jvm-metrics.yaml#L149
https://github.com/open-telemetry/semantic-conventions/blob/13a8238b4dcdd4261751b16012edef6388654f86/model/metrics/jvm-metrics.yaml#L157
> [Editorial] Add missing stable status markers

- .chloggen/661.yaml
- docs/messaging/messaging-spans.md
Fixes #621
This PR adds conventions around span structure for instrumenting settlement operations in messaging workflows. Those conventions have been agreed on in [OTEP 220](https://github.com/open-telemetry/oteps/blob/main/text/trace/0220-messaging-semantic-conventions-span-structure.md#settlement-spans).
Note that the messaging workgroup agreed to exempt conventions around settlement from initial stability of messaging semantic conventions, those will remain experimental while other parts of semantic conventions will be declared stable.
> Add messaging semantic conventions for settlement spans

- docs/database/mssql.md
Update link which now redirects to another url and causes `markdown-link-check` error
> [chore] remove microsoft link to fix PR checks

- .chloggen/509.yaml
- docs/messaging/messaging-spans.md
Fixes open-telemetry/opentelemetry-specification#1466
Based on recent changes from #284, this adds a messaging example illustrating a batch-publishing scenario involving "Publish" and "Create" spans.
> Clarify producer span relationships and add a messaging example for a batch publishing scenario

- docs/database/README.md
- docs/database/database-metrics.md
- docs/database/database-spans.md
Related to #719
This will allow us to start sending PRs as part of the database semantic convention stability effort.
> Add placeholder for database stability transition plan

- docs/messaging/messaging-metrics.md
- docs/messaging/messaging-spans.md
Fixes #720
Added the same warning as was added for database semantic conventions in #733.
I removed the warning about network attributes, as those are also part of database semantic conventions and don't merit a warning there. I'm not aware of any messaging instrumentation that has implemented the prescribed stability mechanisms for network attributes.
> Add placeholder for messaging stabiblity transition plan

- docs/general/trace.md
Fixes #
Now that HTTP Span/Trace Semantic Conventions are marked stable, the overall status should be "Mixed" 
> [chore] Change Traces SemConv Status to Mixed

- .github/workflows/stale-pr.yml
I noticed that the stale bot is applying label to issues, which is not intended. We were using `days-before-stale` which is for PRs and Issues, and now I changed it to the PR specific ones. 
Edit: I went through the issues and removed the label.
> [chore] Exclude issues from stale bot check

- .chloggen/service-instance-id.yaml
- CHANGELOG.md
- docs/resource/README.md
- model/resource/service_experimental.yaml
Related to #311, built on top of https://github.com/open-telemetry/opentelemetry-specification/pull/3222 by @jsuereth.
Enhances the existing `service.instance.id` convention with a common algorithm for SDKs to use when generating that value.
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
> Define a common algorithm for service.instance.id

- .github/workflows/stale-pr.yml
I noticed again that the Stale bot is marking issues as stale and closing them. I found [this thread](https://github.com/actions/stale/issues/1112) and read it again and noticed that actually to opt out from issues, one needs to use `-1` on the defaults, otherwise they will still apply, even though using the `*-pr` config variants, urgh. 
Hopefully, this should be it. 🤞
> [chore] Attempt two: Avoid running stale bot on issues

- docs/attributes-registry/network.md
- model/registry/deprecated/container.yaml
- model/registry/deprecated/k8s.yaml
- model/registry/deprecated/network.yaml
- model/registry/deprecated/system.yaml
Removing attributes introduces a lot of pain to code generation - see #740 or #551 for the context.
I hope we'll be able to automate checks soon with https://github.com/open-telemetry/build-tools/pull/271.
For now, I found some attributes that were removed from yaml in currently unreleased version and this PR is bringing them back.
The goal is to make it easy for the codegen, so no need to mention them in md files.
> [chore] Bring a few attributes that were removed back (as deprecated)

- docs/resource/host.md
escaping the backslash isn't needed here
> Double backslash -> Single backslash

- docs/attributes-registry/url.md
- model/registry/url.yaml
Switches to using code-font for URLs and URL parts in recently added attributes to be consistent across entries in this table: e.g., the table example value is shown as `east` not "east" -- so, this PR switches to using `east` in the footnote too.
> [chore] URL attributes: consistently use code font for URLs and URL parts

- .chloggen/778.yaml
- docs/faas/aws-lambda.md
the problem comes from this "late" addition:
> To avoid potential issues when extracting with an active span context, the xray-lambda propagator SHOULD check if the provided context already has an active span context. If found, the propagator SHOULD return the provided context unmodified.
This is a problem because `xray-lambda` can't check the original context, only the context that is provided to it, which is modified by prior propagators in the chain.
This means if the original carrier has an x-ray context and an x-ray environment variable set, and if the xray propagator is configured as we expect it to be, then the xray-lambda will be either overwritten (if configured first), or will no-op because it detects an existing span context.
Proposed solution: change `xray-lambda` to replace …
> Fix problem in `xray-lambda` propagator definition

- .chloggen/697.yaml
- docs/attributes-registry/messaging.md
- docs/messaging/azure-messaging.md
- model/registry/messaging.yaml
- model/trace/messaging.yaml
- Adds Azure Service Bus-specific attribute describing settlement type (`complete`, `abandon`, `defer`, `dead_letter`)
- Clarifies operation names for settlement and deliver span
* ~~schema-next.yaml~~
> Update Azure messaging: settlement attributes and span names

- .chloggen/780.yaml
- docs/database/cassandra.md
- docs/database/cosmosdb.md
- docs/database/couchdb.md
- docs/database/database-metrics.md
- docs/database/database-spans.md
- docs/database/elasticsearch.md
- docs/database/hbase.md
- docs/database/mongodb.md
- docs/database/mssql.md
- docs/database/redis.md
- docs/database/sql.md
- model/messaging-common.yaml
- model/metrics/database-metrics.yaml
- model/trace/database.yaml
- model/trace/messaging.yaml
Merges connection and call-level attributes for databases.
DB instrumentations in the general case are operating on the logical/public surface level and not always aware of connections.
Separation into connection and call level is also confusing. 
Extracted from #768, related to #690
> Merge DB connection-level and call-level attributes

- .github/workflows/scripts/generate-registry-area-labels.sh
In https://github.com/open-telemetry/semantic-conventions/pull/777 I forgot to uncomment the line which invoked the GH cli to create the labels.
> [chore] Enable creating area labels on push to `main`

- docs/database/database-metrics.md
- docs/faas/faas-metrics.md
- docs/general/metric-requirement-level.md
- docs/messaging/messaging-metrics.md
- docs/rpc/rpc-metrics.md
- docs/runtime/jvm-metrics.md
- docs/system/process-metrics.md
- docs/system/system-metrics.md
- model/README.md
- specification/metrics/metric-requirement-level.md
Fixes #822
Moves the [metric requirement levels](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/metric-requirement-level.md) document to the semconv repo. 
I think I managed to get the git history correct. 
CC @lmolkova
> [chore] Move metric requirement levels doc from spec

- .chloggen/817.yaml
- docs/attributes-registry/network.md
- docs/dotnet/dotnet-http-metrics.md
- docs/dotnet/dotnet-kestrel-metrics.md
- docs/general/attributes.md
- docs/http/http-metrics.md
- docs/http/http-spans.md
- model/registry/network.yaml
Fixes #686
Clarifies that `network.protocol.version` represents negotiated version
> Clarify that `network.protocol.version` represents negotiated version

- .chloggen/738.yaml
- docs/attributes-registry/db.md
- docs/database/elasticsearch.md
- model/registry/db.yaml
- model/registry/deprecated/db.yaml
- model/trace/database.yaml
As per #725 this PR changes the Elasticsearch semantic conventions to use the `db.instance.id` attribute instead of `db.elasticsearch.node.name`.
> Use db.instance.id instead of specific elasticsearch node name attribute

- .chloggen/add_new_container_metrics.yaml
- CHANGELOG.md
- docs/attributes-registry/container.md
- docs/system/container-metrics.md
- model/metrics/container.yaml
- model/registry/container.yaml
This PR adds container related metrics fields as part of https://github.com/open-telemetry/semantic-conventions/issues/72.
Continues https://github.com/open-telemetry/semantic-conventions/pull/87 on top of the project restructuring. 
Based on the comparison between ECS and Otel collector the result is the following (see https://github.com/open-telemetry/semantic-conventions/pull/282#issuecomment-1757735366). 
1) `container.cpu.time` (ok for the Collector implementation: https://github.com/open-telemetry/semantic-conventions/pull/282#issuecomment-1909118310)
2) `container.memory.usage` (more accurate and aligned with system metrics) 
3) `container.disk.io` which has as dimension the already existent `disk.io.direction` (Otel collector only provides the Linux specific metric and hence a …
> Add container metric fields (from ECS)

- .vscode/settings.json
While moving the attributes to the registry, I noticed the auto-complete feature in VSCode wasn't working. Then I saw we still used the old path. Now it works again. I also updated the version to latest.
> Fix path of yaml files for VSCode schema auto completion

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/change_proposal.yaml
- .github/ISSUE_TEMPLATE/new-conventions.yaml
- docs/attributes-registry/README.md
- docs/attributes-registry/feature-flag.md
- docs/feature-flags/feature-flags-logs.md
- docs/feature-flags/feature-flags-spans.md
- model/logs/log-feature_flag.yaml
- model/registry/feature-flag.yaml
- model/trace/feature-flag.yaml
Related to https://github.com/open-telemetry/semantic-conventions/issues/407
Move Feature Flags to the attributes registry
> [chore] Move Feature Flag attributes to the registry

- .github/workflows/scripts/generate-registry-area-labels.sh
The workflow that is supposed to create the labels for new areas https://github.com/open-telemetry/semantic-conventions/actions/runs/8455605243/job/23163472895 is failing because the label already exists. 
I thought it would just skip the ones that already exist, but it seems not. The task fails. So I'm just using `--force` to re-create them. Nothing changes so we should be all good with existing labels.
> [chore] Force create labels in workflow

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/change_proposal.yaml
- .github/ISSUE_TEMPLATE/new-conventions.yaml
- docs/attributes-registry/README.md
- docs/attributes-registry/event.md
- docs/general/events.md
- model/logs/events.yaml
- model/registry/event.yaml
I have moved it to the registry as part of schema clean up but we can decide later if it should stay in this form based on outcome of https://github.com/open-telemetry/semantic-conventions/pull/880
> [chore] move event to registry

- docs/attributes-registry/container.md
- docs/resource/container.md
- model/registry/container.yaml
Corrects `assinged` typo to `assigned` and remakes the markdown.
> [chore] Fix typo in container attributes registry

- .chloggen/890.yaml
- docs/attributes-registry/messaging.md
- docs/messaging/azure-messaging.md
- docs/messaging/gcp-pubsub.md
- docs/messaging/kafka.md
- docs/messaging/messaging-spans.md
- model/registry/deprecated/messaging.yaml
- model/registry/messaging.yaml
- model/trace/messaging.yaml
- schema-next.yaml
Fixes #890
Related to changes made fpr database semantic conventions in #875, this PR ensures consistency and symmetry between `db.operation.name` and `messaging.operation.name`.
> BREAKING: Rename `messaging.operation` to `messaging.operation.name`

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/change_proposal.yaml
- .github/ISSUE_TEMPLATE/new-conventions.yaml
- docs/attributes-registry/system.md
- docs/system/container-metrics.md
- docs/system/system-metrics.md
- model/metrics/system-metrics.yaml
- model/registry/system.yaml
Moves `system.*` attributes to the registry from system metrics. 
> [chore] Move system metric attributes to the registry

- docs/resource/README.md
This fixes what looks like a typo in resource attributes documentation for the `telemetry.distro.*` group.
> [chore] fix typo in resource attributes docs

- docs/database/database-spans.md
- docs/database/elasticsearch.md
- docs/database/mongodb.md
- docs/database/redis.md
- docs/database/sql.md
Follow up for #866
`db.statement` was renamed to `db.query.text`, this PR updates examples and other mentions
> Replace `db.statement` with `db.query.text` in examples

- docs/runtime/jvm-metrics.md
Fixes the navigation title for the JVM docs page:
> Fix title for the JVM docs page

- .chloggen/db_metrics.yaml
- docs/attributes-registry/db.md
- docs/database/database-metrics.md
- model/metrics/database-metrics.yaml
- model/registry/db.yaml
- model/registry/deprecated/db.yaml
- schema-next.yaml
Using tags for now (added moved attributes to the db-generic tag)
> [BREAKING] move attributes from db metrics to the registry

- .chloggen/910.yaml
- model/db-common.yaml
- model/trace/database.yaml
Moves database attributes expected to be used for both traces and metrics to a common file.
> Move common DB attributes

- docs/faas/aws-lambda.md
Seems like lambda SQS part was not adapted to recent messaging conventions changes.
Refs: #517, #913
> [chore] adapt lambda examples to current conventions

- .chloggen/device_app_lifecycle.yaml
- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/change_proposal.yaml
- .github/ISSUE_TEMPLATE/new-conventions.yaml
- .gitignore
- .vscode/settings.json
- docs/attributes-registry/android.md
- docs/attributes-registry/ios.md
- docs/mobile/events.md
- model/logs/mobile-events.yaml
- model/registry/android.yaml
- model/registry/deprecated/android.yaml
- model/registry/deprecated/ios.yaml
Reformat and update the `device.app.lifecycle` event description adds
constraints for the possible values of the `android.state` and `ios.state`.
This is an updated version of #673 where it's using manually created markdown as per the comments in https://github.com/open-telemetry/semantic-conventions/issues/755 before the build tools are available to support the definition.
> Update the device.app.lifecycle event description and constraints

- docs/attributes-registry/db.md
- docs/attributes-registry/messaging.md
- model/registry/db.yaml
- model/registry/messaging.yaml
Related: #887, #917
Moved system-specific attributes in messaging and db registry to their own attribute group, removes tags. 
It provides better auto-generated MD grouping in #917 and simplifies yaml.
> [chore] Split db and messaging registry groups

- .chloggen/975.yaml
- docs/database/database-metrics.md
- docs/database/database-spans.md
- model/db-common.yaml
- model/trace/database.yaml
- Adds `error.type` essential for metrics
- Cleans up redundant yaml
> Database: add error.type to span and metric

- .chloggen/k8s-status.yaml
- docs/attributes-registry/k8s.md
- docs/resource/k8s.md
- model/registry/k8s.yaml
- model/resource/k8s.yaml
Fixes https://github.com/open-telemetry/semantic-conventions/issues/922
> feat: add k8s.container.status.last_terminated_reason resource attribute

- .chloggen/decouple_shared_memory_metric.yaml
- docs/attributes-registry/system.md
- docs/system/system-metrics.md
- model/metrics/system-metrics.yaml
- model/registry/system.yaml
Fixes https://github.com/open-telemetry/semantic-conventions/issues/522
This PR removes the `shared` state from the possible values of the `system.memory.state` metric since it does not contribute to the total. The attribute guidelines mention though:
>  the sum of usage over all attribute values SHOULD be equal to the limit
Hence, we need to remove this state and make it standalone metric.
Note: I'm not sure if [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) needs to be updated since the PR only touches the values' set 🤔
> [metrics/system] Remove shared from system.memory.state values

- .github/workflows/checks.yml
- docfx.json
Fixes #987
Docfx was introduced in the spec repo a while ago - https://github.com/open-telemetry/opentelemetry-specification/pull/742
with the intention to detect broken links.
Docfx v3 we used since https://github.com/open-telemetry/opentelemetry-specification/pull/2285 was in preview and is no longer accessible and not recommended to be used even if built from sources.
Docfx is a site-generator, not a linting tool, there is no (?) documentation on checks against docs it does.
We already have individual markdown lint and link checks.
With all of this I suggest removing docfx since it seems to be unnecessary.
PS: I'll send a similar PR to the spec.
> [chore] Remove docfx as unnecessary

- .markdown_link_check_config.json
https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/dml/dmlConfigConsistency.html is not providing content without user-agent. I have tried some python snippet and it was returning 404 as well. 
With user-agent it is working now.
> [chore] add user agent to the link check

- docs/attributes-registry/jvm.md
- model/metrics/jvm-metrics-experimental.yaml
- model/registry/jvm.yaml
As of this PR - every single attribute is now located in the registry and all attribute_group, event or metric types reference their attributes from the registry.
> [chore] Move last 'loose' attribute to registry.

- .chloggen/1069.yaml
- docs/database/database-spans.md
Fixes #1045
Alternative to #1061
Clarifies that target depends on the operation and if target is not available, instrumentation should not fallback to other options.
E.g. for query like `SELECT * FROM (VALUES (1, 'a'), (2, 'b'), (3, 'c')) AS t (id, name)`  that uses anonymous table, the span name should be `SELECT` and not `SELECT {db.namespace}`.
> Update database span name:  clarify `target` and remove fallback

- .chloggen/1120.yaml
- docs/attributes-registry/db.md
- docs/database/database-metrics.md
- docs/database/database-spans.md
- docs/database/dynamodb.md
- model/registry/db.yaml
Fixes #1023
- renames `cache` to `intersystems_cache` (cache is too broad)
- removes `cloudscape` in favor of `derby` "The [Apache Derby](http://db.apache.org/derby/) project is based upon Cloudscape version 10, which IBM contributed to Apache in 2004."  (see https://en.wikipedia.org/wiki/Apache_Derby, https://db.apache.org/ddlutils/databases/derby.html)
- removed `coldfusion` - it's a [web-development](https://www.adobe.com/products/coldfusion-family.html) platform, not a database. It can work with [different databases](https://helpx.adobe.com/coldfusion/configuring-administering/data-source-management-for-coldfusion.html). 
- `firstsql` - [no longer exists](https://dbdb.io/db/firstsqlj)
- `mssqlcompact` - [discontinued](https://en.wikipedia.org/wiki/SQL_Server_Compact), last released in …
> Clean up database systems

- .github/workflows/stale-pr.yml
Add the `never stale` label, similar to the ones in the collector repos to allow having a PR open without being marked as stale by the GH stale bot.
This is useful, for example for PRs that are blocked by something else but still makes sense. E.g., https://github.com/open-telemetry/semantic-conventions/pull/985
PS: I already created the label in GH.
> [chore] Allow way for PRs to never become stale

- .github/CODEOWNERS
According to the https://github.com/open-telemetry/community/issues/2100 the approvers group was created
I have update codeowners file to reflect changes
> [chore] update codeowners for security

- CHANGELOG.md
With auto-generated changelog (@joaopgrassi 🙇‍♀️)  we no longer need unreleased section (unreleased changes are files in  the `.chloggen` folder). 
But we still have the section in the changelog which has sunk down over time.
I'm suggesting to remove it.
> Remove unreleased section from the middle of the changelog

- docs/database/redis.md
- model/trace/database.yaml
To avoid what could be a common question.
I don't think a change log is necessary, but happy to add one if anyone wishes.
> Editorial: mention that Redis `db.namespace` is a string

- .github/CODEOWNERS
Part of #1177
cc @open-telemetry/semconv-event-approvers
@open-telemetry/specs-semconv-maintainers can you grant @open-telemetry/semconv-event-approvers write permission to this repository before merging this? thanks
> Add semconv-event-approvers to CODEOWNERS

- .github/workflows/scripts/prepare-new-issue.sh
- .gitignore
- Brewfile
- CONTRIBUTING.md
- Makefile
- internal/tools/scripts/update-issue-template-areas.sh
Adding some basic OS detection in scripts and `make` due to the difference between `sed` on MacOs and Linux. Namely, `gsed` (GNU Sed) will be used on MacOs. The contributing guide documents the install under pre-reqs and gives the `brew bundle` command as an optional way to install `gsed` on Mac. This is simply a quality of life improvement for those on Mac.
> [chore] update scripts to detect macos or linux for GNU sed usage

- Makefile
Update to latest release of weaver.
Note: We cannot engage with new JQ fitler functions yet, need to add one that groups by attribute_group (not raw attributes).  cc @lquerel
> (chore): bump to latest weaver version.

- docs/README.md
- docs/cloud-providers/aws-sdk.md
- docs/faas/aws-lambda.md
- docs/general/attributes.md
- docs/general/events.md
- docs/general/logs.md
- docs/general/metrics.md
- docs/non-normative/README.md
- docs/non-normative/compatibility/README.md
- docs/non-normative/compatibility/aws.md
- docs/non-normative/http-migration.md
- docs/non-normative/libraries.md
- internal/tools/update_specification_version.sh
- Fixes #1240
- Moves `supplementary-guidelines` into `docs` and renames it to `non-normative`
- Renames `semantic_conventions_code_generation.md` to `libraries.md` and adjust the `linkTitle` - PTAL
- Fixes links into the supplementary-guideline pages
- Closes #1234 by superseding it
- Moves & renamed the file: `docs/http/migration-guide.md → docs/non-normative/http-migration.md`
- Adds a Hugo redirect alias
- Normalizes a few other page aliases by dropping unnecessary path prefixes
This is what it will look like on the OTel website once integrated:
> <img width="867" alt="image" src="https://github.com/user-attachments/assets/2c9ac8ec-ca68-476e-ba25-90bd5df013ed">
> [editorial] Move supplementary-guidelines into docs

- .chloggen/add_k8s_volume_type.yaml
- docs/attributes-registry/k8s.md
- model/registry/k8s.yaml
- model/resource/k8s.yaml
Fixes https://github.com/open-telemetry/semantic-conventions/issues/1164
Add k8s.volume.{name,type} attributes.
From https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.102.0/receiver/kubeletstatsreceiver/internal/kubelet/conventions.go#L7
* …
> Add k8s.volume.{name,type} attributes

- .chloggen/remove_body_field_ref.yaml
- docs/general/events.md
Fixes #1341 
Removes the option of an event body field to reference / inherit definitions from existing global attribute and providing an optional alias within the event body.
This was discussed during the Event WG Sig meeting on August 9th.
> chore: Remove support for the event `fields` referencing/inheriting definitions from global attributes.

- .github/dependabot.yml
Adds dependabot configuration so that we at least know when semconv tooling versions are out of date and have a chance to update them.
> (chore) Add dependabot config to keep tooling up to date.

- .chloggen/1302.yaml
- Makefile
- docs/general/attribute-naming.md
- policies/attribute_name_collisions.rego
- policies/attribute_name_collisions_test.rego
- policies/yaml_schema.rego
- policies/yaml_schema_test.rego
Fixes open-telemetry/semantic-conventions#1124
- adds checks for attribute, metrics, and event name format 
- adds a note to the attribute naming about current tooling limitations
> Check attribute/metric/event name format

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/change_proposal.yaml
- .github/ISSUE_TEMPLATE/new-conventions.yaml
- .github/workflows/scripts/get-registry-areas.sh
In #1337 I found the sort order to differ between CI and my workstation.
https://github.com/open-telemetry/semantic-conventions/actions/runs/10702984450/job/29674122154?pr=1337 details the difference.
Since BSD, GNU and busybox sort all have a `-d` (dictionary) flag, use that for consistent ordering.
> ci: sort with dictionary mode for compatibility

- docs/attributes-registry/tls.md
- model/registry/deprecated/tls.yaml
Noticed reviewing https://github.com/open-telemetry/semantic-conventions-java/pull/70
> Fix typo in `tls.yaml`

- Makefile
- dependencies.Dockerfile
Fix the docker user flag to properly fetch group and user IDs.
Without this, on linux with GNU Make 4, a new registry component will end up throwing an error:
```
[error] Unable to write file "docs/attributes-registry/csi.md":
```
because it writes out as root rather than the current user.
> ci: fix makefile docker ownership

- docs/non-normative/code-generation.md
> Document semconv version weaver is compatible with and update migration docs

- policies/compatibility.rego
Back-compat checks are failing since 1.28.0 was released with 
```
Violation: Resource 'service' cannot remove required/recommended attributes (missing '{"service.name", "service.version"}')
- Category         : backward_compatibility
- Type             : semconv_attribute
- SemConv group    : service
- SemConv attribute: 
- Provenance: /home/weaver/source
Violation: Resource 'telemetry.sdk' cannot remove required/recommended attributes (missing '{"telemetry.sdk.language", "telemetry.sdk.name", "telemetry.sdk.version"}')
- Category         : backward_compatibility
- Type             : semconv_attribute
- SemConv group    : telemetry.sdk
- SemConv attribute: 
- Provenance: /home/weaver/source
```
E.g. here https://github.com/open-telemetry/semantic-conventions/pull/1454
It happens because …
> Fix failing resource back compat checks

- docs/messaging/gcp-pubsub.md
- docs/messaging/kafka.md
- docs/messaging/messaging-spans.md
Fixes #1465
The mermaid diagrams and the tables use different terms/names for things, which may cause confusion for end-users. This PR attempts to make them a bit more clear.
> Adapt messaging examples/tables 

- docs/http/README.md
I went looking for the http semantic convention migration guide today and couldn't find it since it had been moved out of the http folder.  I'd like the README to link to it, since the http README is the most likely place a user interested in http semconv will start their journey.
> [chore] Add link to migration guide

- docs/http/http-spans.md
Fixes #1541.
As per https://github.com/open-telemetry/semantic-conventions/pull/342 this should be `network.peer.address` instead.
> [chore] Fix HTTP client-server example

- .chloggen/process_uptime.yaml
- docs/system/process-metrics.md
- model/process/metrics.yaml
Fixes #1518 
This PR changes the `process.uptime` metric instrument to a gauge, adding the additional subtext guidance that was part of `system.uptime`.
> process: change process.uptime instrument to gauge

- docs/attributes-registry/service.md
- docs/resource/README.md
- model/service/registry.yaml
Fixes #
This is fixing a CI error here https://github.com/open-telemetry/semantic-conventions/actions/runs/11861560247/job/33059139725?pr=1574
@lmolkova ^^
> [chore] Fixed a dead link for machine id man page

- model/aspnetcore/metrics.yaml
- model/aspnetcore/registry.yaml
- model/aws/registry.yaml
- model/go/registry.yaml
- model/process/registry.yaml
- model/telemetry/registry.yaml
- policies/registry.rego
- policies_test/registry_test.rego
Requirement levels should only appear on spans/metrics/events/profiles definitions. They are  not rendered on the registry attributes and make no sense there. 
Related: https://github.com/open-telemetry/semantic-conventions/pull/1603#discussion_r1853060494
> Remove requirement_level usages from registry and add a policy to check

- .chloggen/1560.yaml
- docs/database/database-spans.md
Addresses the DB part of https://github.com/open-telemetry/semantic-conventions/issues/1536.
Let's polish it for databases and then expand to other conventions (and potentially have a generic guidance).
The intention is to keep exception event part experimental since 
- there doesn't seem to be a consensus or a common approach for it
- span events is going away
> Add section on span status for databases

- .github/CODEOWNERS
This PR amends the CODEOWNERS file with the additional sections owned by @open-telemetry/semconv-system-approvers 
* [N/A] Change log entry added, according to the guidelines in [When to add a changelog entry](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md#when-to-add-a-changelog-entry).
* [N/A] [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.
> [chore] update codeowners with additional system semconv sections

- policies/attribute_name_collisions.rego
- policies_test/attribute_name_collisions_test.rego
Related to https://github.com/open-telemetry/semantic-conventions/pull/1624, https://github.com/open-telemetry/semantic-conventions/pull/1638
Preventing collisions between namespace and attribute name is a protection in case we want to support nested properties in the attributes or add any semantic meaning to namespaces. E.g. having non-deprecated attribute `foo` along with non-deprecated attribute `foo.bar` would be problematic. 
It seems fine however to have deprecated `foo` along with non-deprecated `foo.bar`. 
This PR relaxes the policy and unblocks PRs like #1624 and #1638 (if they are approved).
> Relax collision detection policy to allow collisions between deprecated namespaces and attributes (and vice-versa)

- .chloggen/k8s-migration.yaml
- .github/CODEOWNERS
- docs/non-normative/k8s-migration.md
Part of https://github.com/open-telemetry/semantic-conventions/issues/1537
This PR adds the non-normative k8s semconv migration docs described by https://github.com/open-telemetry/semantic-conventions/issues/1537.
So far it only includes changes from https://github.com/open-telemetry/semantic-conventions/pull/1427 but the goal is to keep adding content in this file as we go.
This PR is blocked until https://github.com/open-telemetry/semantic-conventions/pull/1427 is merged.
/cc @TylerHelmuth
> add k8s semconv migration non-normative doc

- docs/attributes-registry/process.md
- docs/resource/process.md
- model/process/registry.yaml
This is causing a javadoc issue when updating to the latest semconv because it looks like HTML.
Also noticed it isn't rendering in this repo's markdown: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/process.md#process:
I'll open a weaver issue about this. UPDATE: https://github.com/open-telemetry/weaver/issues/519
> Change `<PID>` to `[PID]`

- .vscode/settings.json
- dependencies.Dockerfile
- model/profile/registry.yaml
(and remove the last `allow_custom_values`)
> Update weaver to version 0.12.0

- docs/hardware/common.md
- model/hardware/common-metrics.yaml
Related to https://github.com/prometheus/OpenMetrics/issues/287
The OM 2.0 effort is kicked off, and will start developing on main. This updates the links to OpenMetrics to reference the 1.0 release. The OM project has also been moved into the prometheus github org.
> Update links to openmetrics to reference the v1.0.0 release

- CONTRIBUTING.md
Document that non-OTel conventions (e.g. [Kafka client JMX metrics](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v2.10.0/instrumentation/kafka/kafka-clients/kafka-clients-2.6/library/README.md) or [RabbitMQ Collector Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.116.0/receiver/rabbitmqreceiver)) should not be contributed.
This is long-overdue (https://github.com/open-telemetry/opentelemetry.io/issues/4063, https://github.com/open-telemetry/semantic-conventions/pull/338)
> Document which conventions belong in this repo

- docs/messaging/messaging-spans.md
As found by Cees and discussed in slack https://cloud-native.slack.com/archives/C02Q4AAHDSA/p1736407996891579 the span kind shown in the example tables are not aligned with the recommendation in the conventions for messaging spans. 
This PR makes sure they are correct.
> Messaging: Align span kind in example tables with the spec

- .github/CODEOWNERS
cc @open-telemetry/profiling-approvers
> Add profiling approvers to CODEOWNERS

- .github/workflows/prepare-release.yml
- .github/workflows/scripts/use-cla-approved-github-bot.sh
Here's the PR it creates (tested on my fork): https://github.com/trask/semantic-conventions/pull/4
Will add ensuring spec link versions are up-to-date as part of release automation later.
Will send immediate follow-up PR to update release instructions. Can't update it now b/c I want to include link to run the (not yet created) workflow. (and also b/c of conflicts with #1762)
> Release automation

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/change_proposal.yaml
- .github/ISSUE_TEMPLATE/new-conventions.yaml
- .github/workflows/scripts/prepare-new-issue.sh
we currently label issues that were created using template and don't label blank ones.
> Label all new issues with `triage:needs-triage` label

- .lychee.toml
I suspect these links are only temporarily failing. This happened once before.
> Temporarily ignore failing link

- Makefile
- Would have detected #1799
- Adds a test for missing `tocstop` to markdown-toc target
/cc @trask
> [infra] mardown-lint: report missing tocstop

- docs/database/database-spans.md
The Where_SQL Wikipedia page got deleted https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Where_(SQL) recently and now our link checks are failing.
We have an option to link to the general "SQL Syntax" page, to the operators table, OR use a webarchive link (potentially unstable). For now I went with the first option. 
> [chore] Fix broken SQL Where Wikipedia link

- Makefile
- Adds `normalized-link-check` target that detects non-normalized links as those fixed in #1843
- Adds `normalized-link-check` as a pre-check to the already existing `markdown-link-check` (so it will be check via the existing workflow)
/cc @trask @lmolkova
> [CI] Report non-normalized link from docs into docs

- .chloggen/rename-db-metric-name.yaml
- docs/database/cassandra.md
- docs/database/couchdb.md
- docs/database/dynamodb.md
- docs/database/elasticsearch.md
- docs/database/hbase.md
- docs/database/mariadb.md
- docs/database/mongodb.md
- docs/database/mssql.md
- docs/database/mysql.md
- docs/database/postgresql.md
Part of #1581 , relevant to #1734 
Rename `db.system` to `db.system.name` for metrics, and update the values to be consistent with database spans.
> [db] rename `db.system` to `db.system.name` for metrics and update values

- docs/non-normative/k8s-attributes.md
- Fixes #1971
- Closes #1972 if you agree with this proposal
- Ensures that the offending page has a title, that is, a level-1 heading
- This could be detected by markdown lint, but the check was disabled in #1010, see https://github.com/open-telemetry/semantic-conventions/pull/1010/files#r1985540217. Could the check be re-enabled @lmolkova?
> [editorial] Ensure non-norm/k8s-attr page has a title

- docs/non-normative/k8s-attributes.md
- Fixes a link-check failure:
- Reported in https://github.com/open-telemetry/opentelemetry.io/actions/runs/13736680027/job/38421197046?pr=6122
- https://github.com/open-telemetry/opentelemetry.io/pull/6122
- Drop the page self-link.
- @zeitlinger - since you were the author of the text, do you agree with the suggested change?
- Context: https://github.com/open-telemetry/semantic-conventions/blob/8698e3c5edd3f97d52776abd576fc27fd2e9dba0/docs/non-normative/k8s-attributes.md?plain=1#L19-L22
/cc @lmolkova
> [editorial] Drop page self-link, adjust prose

- docs/attributes-registry/gcp.md
- docs/resource/cloud-provider/gcp/apphub.md
- model/gcp/registry.yaml
Fixes link to AppHub API documentation to use released `v1` instead of `v1alpha`.
> [chore] Fix link to apphub api.

- .chloggen/2020.yaml
- docs/attributes-registry/vcs.md
- docs/cicd/cicd-metrics.md
- model/vcs/registry.yaml
Remove fallback value for vcs provider name attribute because custom values are allowed to be set without the fallback value
Follow up on https://github.com/open-telemetry/semantic-conventions/pull/1997
> [vcs] remove fallback value for vcs provider name attribute

- dependencies.Dockerfile
- docs/dotnet/dotnet-kestrel-metrics.md
- model/kestrel/metrics.yaml
- model/messaging/deprecated/registry-deprecated.yaml
- policies/attribute_name_collisions.rego
- policies_test/attribute_name_collisions_test.rego
Related to #1118 and #1982
The new weaver supports excluding attributes from code generation allowing us to rename `foo_bar` to `foo.bar`!
It can be done by providing the following annotation on attribute to be excluded:
```yaml
- id: messaging.client_id
....
annotations:
code_generation:
exclude: true
```
> Update weaver to 0.14.0 and allow `_` -> `.` renames

- .github/CODEOWNERS
Resolves #2030
I created @open-telemetry/semconv-ios-approvers
and added the following teams to @open-telemetry/semconv-client-approvers team:
- @open-telemetry/semconv-android-approvers
- @open-telemetry/semconv-browser-approvers 
- @open-telemetry/semconv-ios-approvers
I'm planning to delete the @open-telemetry/semconv-mobile-approvers team once this PR is merged.
> Add ios and client codeowners

- .chloggen/add-jvm-gc-cause-attribute.yaml
- docs/attributes-registry/jvm.md
- docs/runtime/jvm-metrics.md
- model/jvm/metrics.yaml
- model/jvm/registry.yaml
Resolves #2065
Based on the discussion with @trask during the Java SIG APAC Meeting on April 17, add garbage collection (GC) causes to the JVM GC-related metrics and ensure they are set to "opt-in."
> Add GC causes to jvm GC related metric

- .github/scripts/prepare-new-pr.sh
> [chore] Enable PR can add area label

- .chloggen/node-label-opt.yaml
- docs/resource/k8s.md
- model/k8s/resources.yaml
Fixes #2079 
Make k8s Node and Pod labels optional (context [here](https://github.com/open-telemetry/semantic-conventions/pull/2168#discussion_r2055650318))
> [k8s] make k8s Node and Pod labels optional

- .chloggen/2145.yaml
- docs/general/how-to-define-semantic-conventions.md
Discussed with @open-telemetry/specs-semconv-maintainers in order to provide more explicit guidance around unblocking #1941 and #2070.
Note that this document (and guidance) is non-normative, and there may be valid reasons to deviate, but it at least makes the preference clear when it comes to modeling these sorts of things.
> Provide guidance on modeling lat/lon, x/y, etc

- templates/registry/markdown/snippet.md.j2
Adds support for `entity` group type, preventing future breaking change with weaver.
See: https://github.com/open-telemetry/weaver/pull/714
> Allow entity group type  in addition to resource.

- docs/database/database-spans.md
in particular I wanted to mention stored procedures, but also added the etc to make it extra clear this is not an exhaustive list
> Expand examples of targets in `db.query.summary`

- docs/database/README.md
- docs/database/database-metrics.md
- docs/database/database-spans.md
- docs/non-normative/db-migration.md
I will follow-up with a PR to update other semconv as well, just want to prioritize review and merging of this for upcoming database stabilization.
> Improve wording of OTEL_SEMCONV_STABILITY_OPT_IN for database semconv

- .chloggen/2218.yaml
- docs/database/database-spans.md
@matt-hensley dug out https://web.cecs.pdx.edu/~len/sql1999.pdf and found that the ANSI SQL standard is CALL
> Clarify `db.query.summary` for stored procedures

- .github/scripts/prepare-new-pr.sh
Fixes #
For this PR https://github.com/open-telemetry/semantic-conventions/pull/2125/files, it has two components as below, we need to cover this case as well.
```
component: [gcp, gen-ai]
```
* If your PR does not need a change log, start the PR title with …
> [chore] enable multiple components

- .github/workflows/checks.yml
- Makefile
- dependencies.Dockerfile
Removes build-tools backwards compatibility check from Semconv.  This is now replaced by weaver, and starting to prevent future development of Semantic Conventions due to erosion of the `build-tools` featureset.
Related: https://github.com/open-telemetry/weaver/issues/227
> (chore) Remove build-tools from semconv build.

- model/aws/registry.yaml
- model/gen-ai/registry.yaml
- model/hardware/host-metrics.yaml
- model/system/deprecated/metrics-deprecated.yaml
- model/system/deprecated/registry-deprecated.yaml
A small follow up after https://github.com/open-telemetry/semantic-conventions/pull/1794
/cc @ppittle @AsakerMohd
> [chore] Move AWS berdock attributes to AWS folder, update stability to development

- .chloggen/2276.yaml
- docs/database/mysql.md
- model/database/spans.yaml
MySQL should be identified as `"mysql"`, not `"microsoft.sql_server"`.
This fixes a regression introduced in https://github.com/open-telemetry/semantic-conventions/commit/a86a51c9325a2ed43b4dc363b008b4bc485b7158#diff-8b7054e134a55e0a1ec2dbd60371b69ee98213984c9973587f428e8f3695ec7a.
> Fix system name for MySQL

- docs/exceptions/exceptions-spans.md
CI failed because https://ruby-doc.org is no longer accessible. https://github.com/open-telemetry/semantic-conventions/actions/runs/15172537474/job/42665853199?pr=2236
Replacing it with the official website: https://docs.ruby-lang.org
> Fix ruby links

- .chloggen/ff-logs-rc.yaml
- docs/feature-flags/README.md
- docs/feature-flags/feature-flags-logs.md
- docs/registry/attributes/feature-flag.md
- model/feature-flags/events.yaml
- model/feature-flags/registry.yaml
Fixes #2249
Mark feature flag logs semantic conventions and all associated attributes as Release Candidate
* ~~[ ] [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.~~
> Mark feature flag semantic conventions as release candidate

- docs/non-normative/k8s-migration.md
The k8s migration guide should link to specific SemConv releases (once those are available) for any introduced breaking changes. This PR fixes the already existing ones.
I could not come up with sth more elegant that'd automate this work but if @open-telemetry/specs-semconv-approvers have any ideas I'd love to know. Otherwise I will keep an eye for keeping them up to date manually 🙂.
Ref to the respective release: https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.30.0
> [chore] Add links to releases for k8s migration guide breaking changes

- .chloggen/add_k8s_container_ready.yaml
- docs/non-normative/k8s-migration.md
- model/k8s/metrics.yaml
Part of https://github.com/open-telemetry/semantic-conventions/issues/2074.
Adds `k8s.container.ready` as defined at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.111.0/receiver/k8sclusterreceiver/documentation.md#k8scontainerready.
| Old (Collector) ![changed](https://img.shields.io/badge/changed-orange?style=flat) | New                                           |
|------------------------------------------------------------------------------------|-----------------------------------------------|
| `k8s.container.ready`                  (type: `gauge`)                             | `k8s.container.ready` (type: `updowncounter`) |
> Add k8s.container.ready metric

- .chloggen/hpa-resource.yaml
- docs/registry/attributes/k8s.md
- docs/resource/k8s.md
- model/k8s/entities.yaml
- model/k8s/registry.yaml
Fixes #2008
Intorduces new attributes for the `k8s.hpa` resource to capture the `scaleTargetRef` fields. 
> [k8s] add k8s.hpa.scaletargetref resource attributes

- docs/messaging/messaging-spans.md
Fixes #2302
- Change left over "Publish" wording for send spans
- Adapt example tables to use `publish` for `messaging.operation.name` and span names where applicable (for pub/sub systems) and sopa
> [chore] Remove usages of 'Publish' spans and adapt example tables

- Makefile
- templates/registry/markdown/snippet.md.j2
Moves to using generic parameters in weaver instead of deprecated attribute registry parameter.
> Remove legacy weaver flag for attribute registry on snippet generation.

- .chloggen/fix_container_limits.yaml
- docs/non-normative/k8s-migration.md
- docs/system/k8s-metrics.md
- model/k8s/metrics.yaml
Fixes https://github.com/open-telemetry/semantic-conventions/issues/2326
Follow up from https://github.com/open-telemetry/semantic-conventions/pull/2178.
Since those have not been released yet I'm not sure if we need a changelog or not.
Latest release: https://github.com/open-telemetry/semantic-conventions/issues/2326
/cc @dashpole @jinja2
> Fix instrument type for .limit/.request container metrics

- docs/system/k8s-metrics.md
- model/k8s/metrics.yaml
We can now define how metrics are associated with entities using the `entity_associations` key. This PR updates the k8s metrics properly.
> [chore] properly define entity_associations for k8s metrics

- docs/messaging/sns.md
- docs/messaging/sqs.md
Fixes #2351
Explicitly set the SQS doc link title to AWS SQS and while at it set the SNS link title to AWS SNS to match
> [chore] Explicitly set the SQS link title #2351

- docs/faas/aws-lambda.md
- docs/hardware/common.md
- docs/hardware/host.md
Fixes #2410 
Updates link title in a couple of locations
> [chore] Update link title #2410

- .github/copilot-instructions.md
Adds [instructions](https://docs.github.com/en/copilot/how-tos/custom-instructions/adding-repository-custom-instructions-for-github-copilot) for review/coding agent based on [contributing.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md) and [general guidance](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/general).
Tried on a few PRs, it seems to produce some reasonable advice, but definitely can be tuned further.
> Add copilot instructions for auto-review

- templates/registry/markdown/entity_namespace.md.j2
Fixes #2458 
Corrects the logic in the template
> [chore] Fix identifying attribute rendering #2458

- docs/general/how-to-define-semantic-conventions.md
Adds a link to the entity modelling guide from the "How to write semantic conventions" guide.  
Additionally, renames "Resource" to "Entity" in the guide.
> Add link to entity modelling guide.

- docs/general/naming.md
Fixes https://github.com/open-telemetry/semantic-conventions/issues/2306
This PR tries to clarfiy the guidance regarding the usage of `.count` for `UpDownCounter`s as it was described at https://github.com/open-telemetry/semantic-conventions/issues/2306.
/cc @trask @lmolkova @braydonk 
> [chore] Clarify .count for updowncounters guidance

- .chloggen/2477.yaml
- .vscode/settings.json
- dependencies.Dockerfile
- model/cloud/registry.yaml
- policies/registry.rego
- policies_test/registry_test.rego
> Add annotation to exclude collisions on `cloud.platform` enum and add policies

- .chloggen/trentm-z_os-enum-value-deprecated-attr.yaml
- docs/registry/attributes/os.md
- docs/registry/entities/os.md
- docs/resource/os.md
- docs/resource/zos.md
- model/os/registry.yaml
This should help with code gen that can use the 'deprecated:' attribute.
'z_os' was recently deprecated in #1687.
Refs: #1687
- I'm not confident this is the correct thing. From following examples of other enum values that were deprecated, this *looks* like the correct thing to do.
- Is a changelog entry required for this? There was a changelog entry for v1.35.0 that included mention of the value being deprecated.
> Add the 'deprecated:' attribute to the recently deprecated 'z_os' enum value

- docs/general/metrics.md
https://unitsofmeasure.org/ucum.html has moved to https://ucum.org/ucum
The former site no longer responds. The latest from the waybackmachine
shows that it matches the new ucum.org content:
https://web.archive.org/web/20250609201256/https://unitsofmeasure.org/ucum
> [chore] Fix link breaking 'make markdown-link-check'

- Makefile
This fixes the breakage of `make normalized-link-check` on macOS by
carefully finding an invocation of `grep ...` that searches docs/ and
model/ but skips "model/README.md" and works with `sh` and `grep` on
macOS and linux.
Fixes: https://github.com/open-telemetry/semantic-conventions/issues/2480
> [chore] Fix 'make check' on macOS

- docs/cicd/cicd-metrics.md
- docs/database/cosmosdb.md
- docs/database/database-metrics.md
- docs/faas/faas-metrics.md
- docs/gen-ai/gen-ai-metrics.md
- docs/hardware/common.md
- docs/hardware/host.md
- docs/otel/sdk-metrics.md
- docs/system/container-metrics.md
- docs/system/k8s-metrics.md
- docs/system/system-metrics.md
- model/azure/cosmosdb-metrics.yaml
- model/container/metrics.yaml
- model/database/metrics.yaml
- model/faas/metrics.yaml
- model/gen-ai/metrics.yaml
- model/hardware/common-metrics.yaml
- model/hardware/host-metrics.yaml
- model/k8s/metrics.yaml
- model/otel/metrics.yaml
- model/system/deprecated/metrics-deprecated.yaml
- model/system/metrics.yaml
- model/vcs/metrics.yaml
- policies/metric_brief_format.rego
- policies_test/metric_brief_format_test.rego
Enforce consistency of metric briefs. Picked ending them with (.), primarily(?) since some of them are two sentences.
Open to alternative arguments, my only specific desire is to have consistency since currently it's about 50-50, and whether to add (.) has come up in multiple reviews of Java specific metrics in the Java repos.
> Enforce consistency of metric briefs

- .chloggen/2526.yaml
- docs/gen-ai/gen-ai-spans.md
- model/gen-ai/spans.yaml
Fixes #2525
Add `gen_ai.operation.name` and `gen_ai.tool.type` attributes for Execute tool span.
> Add operation name and tool type attributes for Execute tool span.

- docs/registry/attributes/cpu.md
- docs/runtime/dotnet-metrics.md
- docs/system/container-metrics.md
- docs/system/process-metrics.md
- docs/system/system-metrics.md
- model/cpu/registry.yaml
Progresses #2555
Sets the brief property for enum members to human readable version of the value text.
> [chore] Set enum briefs for CPU

- docs/how-to-write-conventions/README.md
- policies/attribute_types.rego
- policies_test/attribute_types_test.rego
Following up on https://github.com/open-telemetry/opentelemetry-specification/pull/4485, this PR relaxes `any` attribute usage on spans.
We're actively experimenting with complex attributes in GenAI SIG #2179 where we have chat history recorded on spans or events. 
While OTel implementations don't allow complex attributes on spans, we suggest to record them as JSON strings as a temporary workaround in unstable instrumentations.
> Allow complex attributes on spans

- docs/registry/attributes/enduser.md
- model/enduser/deprecated/registry-deprecated.yaml
Progresses #2602
This uses a structured rename deprecation for the Enduser
> [chore] Use rename deprecations for Enduser #2602

- docs/database/cassandra.md
- docs/registry/attributes/cassandra.md
- model/cassandra/registry.yaml
Progresses #2555
Sets the brief property for enum members to human readable version of the value text.
> [chore] Set enum briefs for Cassandra

- docs/database/cosmosdb.md
- docs/registry/attributes/azure.md
- model/azure/registry.yaml
Progresses #2555
Sets the brief property for enum members to human readable version of the value text.
> [chore] Set enum briefs for Azure

- docs/registry/attributes/aws.md
- docs/registry/entities/aws.md
- docs/resource/cloud-provider/aws/ecs.md
- model/aws/registry.yaml
Progresses #2555
Sets the brief property for enum members to human readable version of the value text.
> [chore] Set enum briefs for AWS

- Makefile
The make targets are failing on Windows due to command-line length limitations.
This PR fixes it by not creating and passing the large `ALL_DOCS` on the command line.
> Fix make targets on Windows

- docs/gen-ai/gen-ai-spans.md
- docs/gen-ai/non-normative/examples-llm-calls.md
Fixes #2179 
Fix some typos in documents. cc @lmolkova 
> [chore] Fix some typos in documents of generative AI

- CHANGELOG.md
- docs/database/cassandra.md
- docs/database/cosmosdb.md
- docs/database/database-spans.md
- docs/database/mariadb.md
- docs/database/mysql.md
- docs/database/oracledb.md
- docs/database/postgresql.md
- docs/database/sql-server.md
- docs/database/sql.md
- docs/registry/attributes/db.md
- model/database/registry.yaml
Fixes #2667
Clarify that the casing of any named parameters should be left as-is.
Rather than introduce a new example, changes the casing of the existing example.
> [chore] Clarify behaviour for db.query.parameter.<key>

- docs/how-to-write-conventions/README.md
Fixes #2751
Adds more guidance on how to define attributes - in this case how to approach *.system.name enums:
- no need to be exhaustive
- constant along with convention is encouraged
- only stable instrumentations need to document all constants
> Document that *.system.name enums are not exhaustive and should not be added without conventions

- docs/feature-flags/feature-flags-events.md
Follow-up to https://github.com/open-telemetry/semantic-conventions/pull/2781
> editorial: add alias for feature flag logs-events rename

- docs/non-normative/groups/system/cpu-metrics-guidelines.md
Fixes https://github.com/open-telemetry/semantic-conventions/issues/2177
Prio art:
1. [System CPU Utilization gist](https://gist.github.com/braydonk/b2381da98dc3c4fd5ac064045d556634) by Braydon Kains (@braydonk). PromQL queries come in this PR come from this gist
2. Attempt to introduce an [optional normalized total CPU utilization metric](https://github.com/open-telemetry/semantic-conventions/issues/1873)
Note: if the PR is touching an area that is not listed in the [existing areas](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/README.md), or the area does not have sufficient [domain experts coverage](https://github.com/open-telemetry/semantic-conventions/blob/main/.github/CODEOWNERS), the PR might be tagged …
> [chore] Add guideline for cpu metrics' requirement level

- .chloggen/1714-cicd-logs-guidance.yaml
- docs/cicd/README.md
- docs/cicd/cicd-logs.md
Fixes #1714
For discoverability we give a short description of CI/CD logs and link to general log SemConv, the specification for log correlation with spans and CICD resources.
* Links to the prototypes or existing instrumentations (when adding or changing conventions) → NA
> Add CICD conventions for logs

- docs/non-normative/groups/system/cpu-metrics-guidelines.md
- Followup to #2804
- Fixes issue reported by OTel.io build: https://github.com/open-telemetry/opentelemetry.io/actions/runs/18093975280/job/51481031511?pr=7863
> WARN: tmp/semconv/docs/non-normative/groups/system/cpu-metrics-guidelines.md: no level 1 heading found, so no page will be generated at scripts/content-modules/adjust-pages.pl line 149
/cc @open-telemetry/docs-approvers
> [editorial] cpu-metrics-guidelines: make page title a H1

- docs/cloud-providers/aws-sdk.md
- docs/database/dynamodb.md
- docs/object-stores/s3.md
- docs/registry/attributes/rpc.md
- model/rpc/common.yaml
- model/rpc/registry.yaml
Remove notes from rpc.service/method attribute as they only apply to the rpc spans as discussed in #2736 as such they have been added to the span allowing them to be removed from metrics.
> [chore] Remove notes from rpc base

- .chloggen/rename_process_context_switch_type.yaml
- docs/registry/attributes/process.md
- docs/system/process-metrics.md
- model/process/deprecated/registry-deprecated.yaml
- model/process/metrics.yaml
- model/process/registry.yaml
Fixes https://github.com/open-telemetry/semantic-conventions/issues/1501
This PR renames `process.context_switch_type` to `process.context_switch.type`.
> [process] Rename process.context_switch_type to process.context_switch.type
