README.md
Fixed the team names, some links, as well as @MovieStoreGuy's and my name 🙂
=> Fix contributor names and teams

.github/CODEOWNERS
=> Remove tech committee from maintainers.  Semconv will have its own set.

specification/metrics/semantic_conventions/runtime-environment-metrics.md
See corresponding PR in [specification](https://github.com/open-telemetry/opentelemetry-specification/pull/3543).
=> Fix broken jvm runtime links

CHANGELOG.md, semantic_conventions/metrics/process-runtime-jvm-metrics-experimental.yaml, semantic_conventions/metrics/process-runtime-jvm-metrics.yaml, specification/metrics/semantic_conventions/runtime-environment-metrics.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3419
=> Split out truly experimental JVM metrics

CHANGELOG.md
Follow up from #27, adding the entry to the correct place in the markdown file
=> Move AWS change log entry to semconv section

CHANGELOG.md
=> Add in changelog history.

.github/CODEOWNERS, README.md
- Only adds @trask to make sure I did this right.
- Happy to add more from HTTP or JVM WG that aren't already general semconv approvers.
=> Set up new approvers for HTTP/JVM semconv. 

.github/CODEOWNERS
Adding @open-telemetry/semconv-http-approvers and @open-telemetry/semconv-jvm-approvers.
=> Update CODEOWNERS with approver sub-groups

internal/tools/schema_check.sh
=> Re-enable the schema check to look at the website.

.github/CODEOWNERS
Fixes #294
Adds system semantic conventions approvers for:
1. `system.` metrics 
2. `host.` resource attributes
=> [.github/CODEOWNERS] Add semconv system approvers

schema-next.yaml
Fixes schema transformation added in #229
=> Fix schema transformation added in #229

CHANGELOG.md, schema-next.yaml, schemas/1.22.0
This PR updates the repository for the 1.22.0 release.
AFTER this PR is submitted, a tag will be issued, a release created on GITHUB and the schema for 1.22.0 will be served live.
Please check whether all desired changes are included!
=> Stage 1.22.0 release for review.

CHANGELOG.md
We would require all PRs to put their changelog entry under the appropriate section.
=> Add sections to changelog for easier user consumption on release.

docs/attributes-registry/url.md, docs/database/elasticsearch.md, docs/http/http-spans.md, docs/url/url.md, model/registry/url.yaml
Replace `should` with normative `SHOULD` in 3 places in `url.yaml`.
=> should -> SHOULD

.github/CODEOWNERS
=> Updated CODEOWNERS for http-approvers

.github/workflows/checks.yml, CHANGELOG.md, schemas/1.23.1
=> Add 1.23.1 schema and prepare changelog for patch release

CHANGELOG.md, schema-next.yaml
Followup to PR #530 to add the changes to the changelog and schema.
=> Add io direction attributes to Changelog

CHANGELOG.md, schema-next.yaml, schemas/1.24.0
This release will mark JVM metrics stable.
@trask do you want to include #612?
=> Staging the 1.24.0 release

docs/runtime/jvm-metrics.md
Addresses https://github.com/open-telemetry/opentelemetry-specification/issues/3311#issuecomment-1854738782
cc @vijaysun-omr @donbourne
Change "J9" to "OpenJ9".
=> Editorial: change "J9" to "OpenJ9"

docs/resource/README.md, model/resource/service.yaml, model/resource/telemetry.yaml
=> Reflect service.*, telemetry.sdk.* stability in model

docs/http/http-spans.md
=> (editorial) Update http.resend_count references to http.request.resend_count

.chloggen/TEMPLATE.yaml, CONTRIBUTING.md
Just a few small fixes around the changelog generation. 
I am fighting with the changelog automation over in #566 and tried to follow the instructions and noticed a few things along the way.
=> A few small documentation things around changelog generation.

docs/README.md, docs/attributes-registry/host.md, docs/attributes-registry/os.md, docs/attributes-registry/url.md, docs/cloud-providers/README.md, docs/cloudevents/README.md, docs/database/README.md, docs/dotnet/README.md, docs/exceptions/README.md, docs/faas/README.md, docs/feature-flags/README.md, docs/general/README.md, docs/http/README.md, docs/messaging/README.md, docs/mobile/README.md, docs/object-stores/README.md, docs/resource/README.md, docs/resource/cloud-provider/README.md, docs/resource/cloud-provider/aws/README.md, docs/resource/cloud-provider/gcp/README.md, docs/rpc/README.md, docs/system/README.md, docs/url/README.md
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/3922
/cc @theletterf @svrnm
=> [editorial] Fix path base in Hugo front matter

README.md
In recognition of her dedication, thorough code reviews and maintenance of our crucial `build-tools` tooling.
Looking forward to your continued contributions @lmolkova !
=> Add Liudmila to semconv maintainers.

docs/general/attribute-naming.md
=> [chore] Add recommendation for lowercase attribute names

package.json
Similar to in the spec https://github.com/open-telemetry/opentelemetry-specification/pull/3934
=> [chore] Pin markdown-link-check version

Makefile
=> [chore] Fix md generation commands in makefile

model/trace/faas.yaml
Removes constraints from faas semconv - they are not needed and don't change anything.
Related to https://github.com/open-telemetry/build-tools/issues/293
=> [chore] Remove constraints from faas

README.md
In recognition of excellent work across all semantic conventions.
Thanks for the contributions @pyohannes !! Looking forward to more.
=> Move Johannes to maintainer.

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/change_proposal.yaml, .github/ISSUE_TEMPLATE/new-conventions.yaml, docs/attributes-registry/README.md, docs/attributes-registry/graphql.md, docs/graphql/graphql-spans.md, model/registry/graphql.yaml, model/trace/instrumentation/graphql.yml
=> [chore] move graphql to registry

docs/attributes-registry/README.md
=> Adjust readme for the registry to include stability level.

docs/database/cosmosdb.md, docs/database/database-spans.md, docs/database/elasticsearch.md, docs/database/mongodb.md, docs/database/redis.md, docs/database/sql.md, model/trace/instrumentation/aws-sdk.yml
=> Update references from `db.operation` to `db.operation.name`

docs/database/database-spans.md
=> Update missing modification from `db.operation` to `db.operation.name`

docs/messaging/azure-messaging.md
Fixes https://github.com/open-telemetry/opentelemetry.io/issues/4326
=> Fix the linkTitle for Azure Messaging

docs/exceptions/README.md
Both of the linked documents are marked stable.
(thanks @dyladan for spotting)
=> Fix markdown status of exceptions

model/registry/aws.yaml, model/registry/otel.yaml, model/registry/peer.yaml
=> [chore] fix type of registry groups

.github/workflows/checks.yml, Makefile, docs/attributes-registry/messaging.md
Apparently we never check that registry is up to date
=> Add registry md check and fix violations

.markdown_link_check_config.json
=> [chore] Fix typo

Makefile, docs/object-stores/s3.md, docs/resource/k8s.md
Some changes came with the latest weaver breaking the CI.
=> Fix CI: regenerate semconv with latest weaver

Makefile
Moves to use the latest stable weaver release.  Should have less breakages during weaver development moving to stable versions.
=> [chore] Move to latest weaver release.

docs/attributes-registry/aws.md, docs/attributes-registry/cloudevents.md, docs/attributes-registry/db.md, docs/attributes-registry/gcp.md, docs/attributes-registry/gen-ai.md, docs/attributes-registry/graphql.md, docs/attributes-registry/http.md, docs/attributes-registry/ios.md, docs/attributes-registry/jvm.md, docs/attributes-registry/messaging.md, docs/attributes-registry/oci.md, docs/attributes-registry/opentracing.md, docs/attributes-registry/os.md, docs/attributes-registry/otel.md, docs/attributes-registry/rpc.md, docs/attributes-registry/signalr.md, docs/attributes-registry/tls.md, docs/attributes-registry/url.md, templates/registry/markdown/attribute_namespace.md.j2
`Aws attributes` to `AWS attributes`
=> [chore] use correct acronym for second headline

model/trace/messaging.yaml
=> [chore] Fix GH yaml check warning

Makefile
Bump to v0.5.0.  This should enable new policy-based features and unblock #1014
=> Bump weaver to latest version.

docs/general/profiles.md
The `linkTitle` is not correct
- Change from `Logs` to `Profiles`
=> [chore] Update profiles.md

README.md
Moving @Oberon00, @jamesmoessis, and @MovieStoreGuy to emeritus approvers. 
Thanks a lot folks for all the contributions and helping bootstrap semantic conventions here and in the spec repo.
=> Update approvers 

.vscode/settings.json, dependencies.Dockerfile, model/android/resources.yaml, model/aws/ecs-resources.yaml, model/aws/eks-resources.yaml, model/aws/lambda-spans.yaml, model/aws/logs-resources.yaml, model/aws/sdk-spans.yml, model/browser/resources.yaml, model/cloud/resources.yaml, model/cloudfoundry/resources.yaml, model/container/resources.yaml, model/database/spans.yaml, model/deployment/resources.yaml, model/device/resources.yaml, model/faas/resources.yaml, model/faas/spans.yaml, model/feature-flags/logs.yaml, model/gcp/cloud-run-resources.yaml, model/gcp/gce-resources.yaml, model/graphql/spans.yml, model/heroku/resources.yaml, model/host/resources.yaml, model/k8s/resources.yaml, model/os/resources.yaml, model/otel/resources.yaml, model/process/resources.yaml, model/rpc/spans.yaml, model/webengine/resources.yaml
See https://github.com/open-telemetry/semantic-conventions/pull/1653#issuecomment-2521261926
=> Update weaver and add missing stability levels to spans, resources and events

.github/CODEOWNERS
Add code owners for the http and db migration guides
=> Add code owners for the http and db migration guides

.lychee.toml, docs/general/naming.md, docs/hardware/README.md, docs/runtime/README.md, docs/system/hardware-metrics.md, docs/system/process-metrics.md, docs/system/system-metrics.md
Just discovered a bug I introduced when switching from command-line config to toml config 🙈
=> Fix lychee toml config

.chloggen/1655.yaml, .chloggen/1719.yaml
=> [chore] updated changelog for gen-ai

CONTRIBUTING.md
=> [chore] Added content for update toc

docs/general/naming.md
This page was refactored/renamed in #1694.
Found issue when running https://github.com/open-telemetry/opentelemetry.io/actions/workflows/build-dev.yml.
cc @open-telemetry/docs-approvers
=> Fix website linking

docs/general/trace.md
=> [editorial] Fix alias in general/trace.md

.github/workflows/auto-update-spec-repo-links.yml
/cc @trask @open-telemetry/docs-maintainers
=> [CI] Run auto-update script only under otel org

docs/attributes-registry/url.md, docs/general/metrics.md, model/url/registry.yaml
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/6409
=> [editorial] Use canonical https URLs

.github/CODEOWNERS
cc @open-telemetry/semconv-android-approvers
=> Add android codeowners

CONTRIBUTING.md
=> [chore] Added yamllint check

.github/workflows/changelog.yml
Merge queue builds can't reference PR labels.
=> Another merge queue fix

docs/database/redis.md, model/database/spans.yaml
=> Remove field values from Redis query examples

docs/non-normative/code-generation.md
Small typo fix.  Repeated words from previous sentence. 
=> [chore] Fix stray sentence fragment

.chloggen/job-labels-annotations.yaml, docs/attributes-registry/k8s.md, docs/resource/k8s.md, model/k8s/registry.yaml, model/k8s/resources.yaml
Fixes #2137 
Introduction of semantic conventions for k8s Job labels and annotations
=> [k8s] Introduce semantic conventions for k8s Job labels and annotations

.chloggen/namespaces-labels-annotations.yaml, docs/attributes-registry/k8s.md, docs/resource/k8s.md, model/k8s/registry.yaml, model/k8s/resources.yaml
Fixes #2131 
Introduction of semantic conventions for k8s Namespace labels and annotations
=> [k8s] Introduce semantic conventions for k8s Namespace labels and annotations

.chloggen/daemonsets-labels-annotations.yaml, docs/attributes-registry/k8s.md, docs/resource/k8s.md, model/k8s/registry.yaml, model/k8s/resources.yaml
Fixes #2136 
Introduction of semantic conventions for k8s DaemonSet labels and annotations
=> [k8s] Introduce semantic conventions for k8s DaemonSet labels and annotations

docs/non-normative/db-migration.md
Oops, would have been nice to remove this before the tagged release 🤷‍♂️
=> Remove warning

docs/http/http-spans.md, model/http/spans.yaml
=> [chore] Fix typo in http client SpanKind

policies_test/yaml_schema_test.rego
Adds test for https://github.com/open-telemetry/build-tools/issues/40
=> Add test for enum member id format

docs/non-normative/code-generation.md, model/azure/cosmosdb-metrics.yaml, model/cpu/registry.yaml, model/database/common.yaml, model/database/metrics.yaml, model/database/spans.yaml, model/feature-flags/events.yaml, model/gen-ai/spans.yaml, model/kestrel/metrics.yaml, model/messaging/common.yaml, model/messaging/spans.yaml
Updating codegen guide after sunsetting build tools - https://github.com/open-telemetry/build-tools/pull/404, https://github.com/open-telemetry/build-tools/issues/322
=> Remove mentions of build-tools semconvgen

CHANGELOG.md
reported by @pellared https://cloud-native.slack.com/archives/C041APFBYQP/p1747766118848359
=> Fix link in v1.33.0 change log

docs/registry/attributes/heroku.md, model/heroku/registry.yaml
Fixes #2344 
Updates the heroku description so it isn't referring to Android
=> [chore] fix heroku description #2344 

docs/registry/attributes/deployment.md, model/deployment/deprecated/registry-deprecated.yaml
Remove quotes as they're being rendered in the [live documentation](https://opentelemetry.io/docs/specs/semconv/registry/attributes/deployment/#deployment-deprecated-attributes).
=> [chore] Remove quotes from values

.github/workflows/prepare-release.yml
See https://github.com/open-telemetry/sig-security/issues/148 for details.
cc @trask
=> Add permissions that were missed on the first pass

README.md
Thanks for everything @pyohannes, hope to see you back here some day!
=> Move Johannes Tax to Emeritus Maintainer

docs/registry/attributes/android.md, docs/registry/attributes/app.md, docs/registry/attributes/device.md, docs/registry/entities/android.md, docs/registry/entities/app.md, docs/registry/entities/device.md, docs/resource/android.md, docs/resource/device.md, model/android/registry.yaml, model/app/registry.yaml, model/device/registry.yaml
=> Better link text

CHANGELOG.md
(I already fixed the formatting when making the GitHub release)
=> Small change log formatting

docs/hardware/cpu.md, docs/hardware/disk-controller.md, docs/hardware/enclosure.md, docs/hardware/fan.md, docs/hardware/gpu.md, docs/hardware/logical-disk.md, docs/hardware/memory.md, docs/hardware/network.md, docs/hardware/physical-disk.md, docs/hardware/power-supply.md, docs/hardware/tape-drive.md, docs/hardware/temperature.md, docs/hardware/voltage.md
One of the problems in https://github.com/open-telemetry/semantic-conventions/issues/2690#issuecomment-3235276173
why link-check didn't detect it - https://github.com/open-telemetry/semantic-conventions/issues/2690#issuecomment-3235455543
=> Fix metrics requirement level link

docs/registry/attributes/db.md, docs/registry/attributes/vcs.md, model/database/deprecated/registry-deprecated.yaml, model/vcs/deprecated/registry-deprecated.yaml
Removes quotes from briefs for multi line briefs as they were being rendered in docs
=> [chore] Remove un-necessary quotes

.github/CODEOWNERS
cc @open-telemetry/semconv-client-approvers
(related: #2695)
=> Add session CODEOWNERS

docs/database/cosmosdb.md, docs/registry/attributes/azure.md, model/azure/registry.yaml
=> Update broken link to Azure region locations API

.chloggen/2805.yaml, docs/rpc/README.md, docs/rpc/rpc-metrics.md, docs/rpc/rpc-spans.md
Fixes #2718
Copied the warning over from Database semantic conventions.
=> Update RPC stability warning
